### PR TITLE
Fix https://github.com/mupen64plus/mupen64plus-core/issues/883

### PR DESCRIPTION
**Pull request by Gillou68310**

### CODE REVIEW

**Comment by Gillou68310** [comment]
@dmrlawson could you confirm that this fixes https://github.com/mupen64plus/mupen64plus-core/pull/884/commits/c72fb840ae7105bfc93e6122b1582932d7d571fb?

**Comment by dmrlawson** [comment]
Yep, game starts now. Thanks!

**Comment by Gillou68310** [comment]
Cool thanks for testing!

**Comment by loganmc10** [comment]
I received a report that Indiana Jones is freezing using the new dynarec (and wasn't before): https://github.com/loganmc10/m64p/issues/202 Sorry I haven't had a chance to test yet, but this is the only change to the new dynarec that could have caused it

**Comment by Jj0YzL5nvJ** [comment]
I tested and can ratify Logan's suspicions.

**Pull request merged**
