### PR TITLE
Be more selective on which interrupts we can load or save states

### PR DESCRIPTION
**Pull request by fzurita**
This seems to fix the issue encountered in https://github.com/mupen64plus/mupen64plus-core/issues/294.

I have no idea if this is the correct fix or what kind of side effects it could have, but after making this change, I'm unable to reproduce the above issue.

### CODE REVIEW

**Comment by loganmc10** [comment]
Is this still a problem? I've still never been able to reproduce this issue on Android

**Comment by fzurita** [comment]
I don't know, I have this workaround included in the play store version of Mupen64plus AE so I don't see it there and that's the one I usually use.

I'll give it a shot soon.

**Comment by fzurita** [comment]
I tried for a while and couldn't make it happen. It was very easily reproducible for me before. I'll close and re-open if the issue shows up again.

**Comment by fzurita** [comment]
I just had the issue happen in Golden Eye. I guess it's still happening but much rarer.

**Comment by loganmc10** [comment]
Do you still have the save state? I remember when I was testing this, I did have GoldenEye freeze when trying to load the save state once (on Android), but when I tried to open the save state using the cached interpreter, it worked, just not with the arm dynarec

**Comment by fzurita** [comment]
I'm pretty sure the issue is due to TLB, on the save states where the issue happened, TLB address translation did not seem to be working correctly. the new dynarec has its own TLB implementation. 

I'll check if I still have the save state.

**Comment by fzurita** [comment]
Here is the save state:

[golden_eye_freeze.sav.zip](https://github.com/mupen64plus/mupen64plus-core/files/1318490/golden_eye_freeze.sav.zip)

**Comment by loganmc10** [comment]
Yeah I can open that savestate on my PC no problem, doesn't freeze. I think it's something up with the new dynarec

**Pull request closed without merging**
