### PR TITLE
Various Mac-related build fixes

### PR DESCRIPTION
**Pull request by comex**
Some Makefile fixes, fixes for Clang warnings, and revamping asm_defines because the old version didn't seem to work properly on Mac.  Please see the commit messages for details.

### CODE REVIEW

**Comment by bsmiles32** [comment]
Clever way of avoiding objdump/nm. A bit unorthodox but does the job well :)
Tested on my setup with gcc 7.1.1 and everything seems OK.
Can someone test this on msvc to confirm no regression happened ?

**Comment by bsmiles32** [comment]
@loganmc10, @Gillou68310  Can you also test on your setup if it works for you please ?

**Comment by loganmc10** [comment]
It has some conflicts with the current master

**Comment by bsmiles32** [comment]
@loganmc10 : Ok, I resolved the conflicts. Can you test ?

**Comment by loganmc10** [comment]
I tested 32 and 64 bit Windows using MinGW and 64-bit Linux using GCC. No issues. I also tested my Raspberry Pi over SSH (it compiled and ran without crashing, but I can't see the screen to verify what it looks like) and there were no issues.

The only thing I didn't test was Visual Studio, since I don't have that setup.

**Comment by bsmiles32** [comment]
Thanks ! Will wait for confirmation that msvc works before merging.

**Comment by loganmc10** [comment]
@comex I see you updated the Visual Studio makefile, did you test this on Visual Studio? We don't seem to be getting any takers for testing on VS

**Comment by Gillou68310** [comment]
I check on VS and everything looks good. @bsmiles32 why did you merge the master branch into mac-fixes instead of rebasing against master?

**Comment by bsmiles32** [comment]
@Gillou68310 : I just used the "online Github editor" to resolve the conflict and that's what I got by clicking the various buttons... Not (yet) a git expert sadly.

**Comment by Gillou68310** [comment]
I see, the problem is that it makes the history unreadable as the merged commits are not placed on top of master.

**Comment by Gillou68310** [comment]
Try to use the rebase function as much as you can.

**Comment by loganmc10** [comment]
Yeah I agree that the "Merge branch master into...." commits are a little scary. On GitHub it's really hard to see what the actual impact of those commits is.

I realized though that doing a ```git show 949625d``` in Linux will show you the "actual impact" of the commit, so it's a little less scary, but yeah doing a ```git rebase master``` and manually resolving the merge conflicts makes it a lot cleaner

**Comment by charlemagnelasse** [comment]
It looks like this broke the build. It stops with:

    awk -v dest_dir="../../src/asm_defines" -f ../../tools/gen_asm_defines.awk "_obj/asm_defines/asm_defines.o"                                                                                                                                                               
        AS  _obj/device/r4300/x86_64/dyna_start.o                                                                                                                                                                                                                             
    ../../src/device/r4300/x86_64/dyna_start.asm:21: fatal: unable to open include file `asm_defines_nasm.h'                                                                                                                                                                  
    Makefile:697: recipe for target '_obj/device/r4300/x86_64/dyna_start.o' failed                                                                                                                                                                                            
    make: *** [_obj/device/r4300/x86_64/dyna_start.o] Error 1                                                                                                                                                                                                                 
    make: *** Waiting for unfinished jobs....

Please revert 7b6ffc26a2004f543e0fbb10df5c1cce94fa1ba8 to fix this problem.

**Comment by charlemagnelasse** [comment]
@bsmiles32  This awk script is not compatible with mawk (default on many systems). Either do following change

    -AWK      ?= awk
    +AWK      ?= gawk

Or revert the commit 7b6ffc26a2004f543e0fbb10df5c1cce94fa1ba8

**Comment by comex** [comment]
My bad.  I just submitted #322 to fix this.

**Pull request merged**
