### PR TITLE
New dynarec fixes [WIP]

### PR DESCRIPTION
**Pull request by Gillou68310**
https://github.com/mupen64plus/mupen64plus-core/issues/288

### CODE REVIEW

**Comment by loganmc10** [comment]
Just tested this (including the WDC fix). WDC/Stunt Racer and Indiana Jones are working now, however Smash Bros no longer boots.

**Comment by Gillou68310** [comment]
Thanks could you check which one of the 2 commits broke smash bros? I guess it would be the first one. Did you tested on arm or x86?

**Comment by loganmc10** [comment]
I do that in a bit, I tested x86 (windows)

**Comment by Gillou68310** [comment]
Ok my fix for Indi on x86 is wrong. I can't force the shift value to be allocated to ECX because it's likely to break the register mapping when in a delay slot. I need to find another workaround!

**Comment by Gillou68310** [comment]
However my fix for ARM should be ok!

**Comment by Gillou68310** [comment]
@loganmc10 I updated my fixes, could you check again for regressions?

**Comment by loganmc10** [comment]
Smash Bros works now. Pokemon Puzzle League and both Banjo games now fail at the assert(0) in MULTDIV. Pokemon Puzzle League used to fail at a different assert (https://github.com/mupen64plus/mupen64plus-core/issues/304), but I believe the Banjo games used to work.

**Comment by Gillou68310** [comment]
Oups sorry I forgot to remove it. You can safely remove it if you want to do more tests ;-)

**Comment by loganmc10** [comment]
Ok yeah removing that assert allows those 3 games to work normally.

I just ran across an issue in Conkers though:

```
Assertion failed!
File: ../../src/device/r4300/new_dynarec/x86/assem_x86.c, Line 777

Expression: rm<8
```

Doesn't happen in the current master, this is with x86

**Comment by Gillou68310** [comment]
Thanks I'll investigate the issue!

**Comment by Gillou68310** [comment]
@loganmc10 I updated the fix for WDC. It should fix the issue in CBFD.

**Comment by loganmc10** [comment]
Yep looks good to me now. I did all my testing on x86, not arm

**Comment by fzurita** [comment]
Ok, sorry for the delay. I just tried Indiana Jones with ARM Android, it's not crashing where it used to crash any more. I also tried several other games as sanity checks with no issue.

This looks good to me,

**Comment by Gillou68310** [comment]
Thanks for testing!
I just pushed a fix for Glover BTW ;-)

**Comment by loganmc10** [comment]
Does that fix perhaps also fix https://github.com/mupen64plus/mupen64plus-core/issues/304? I notice it modifies the assert that is failing in that issue

**Comment by Gillou68310** [comment]
I didn't check but last time I invatigated this issue I think the problem was elsewhere. I need to double check!

**Comment by fzurita** [comment]
Nice work, I'll try to test it soon.

**Comment by fzurita** [comment]
I can confirm that the glover fix works correctly. I did some sanity checks with a few common games and nothing seems to break.

**Comment by Narann** [comment]
@fzurita could you rebase on master so the TravisCI doesn't bug anymore.

**Comment by Gillou68310** [comment]
Done

**Comment by Narann** [comment]
It's passing the build. Is this ready for merge? As it's not that much, I would have loved to have @bsmiles32 view on this.

**Comment by Gillou68310** [comment]
Nope it's not ready yet, I'm still working on the following issues:
https://github.com/mupen64plus/mupen64plus-core/issues/286 https://github.com/mupen64plus/mupen64plus-core/issues/304 https://github.com/mupen64plus/mupen64plus-core/issues/305

Also the fix for Glover might change because it accidentally fix https://github.com/mupen64plus/mupen64plus-core/issues/304 while it's not the root cause of the issue.

https://github.com/mupen64plus/mupen64plus-core/issues/385 will be for another PR

**Comment by loganmc10** [comment]
I would suggest perhaps merging this PR, and then submitting a new PR for the future fixes. The current fixes have been tested and we know they fix these games.

**Comment by Gillou68310** [comment]
The fix for glover is not mergeable yet but the fix for WDC and indi could definitely be merged. Since I'm busy with other things right now I think it's a good idea to merge the 2 first commits until I come back to this!

**Comment by Narann** [comment]
@Gillou68310 You should have merge permission. Haven't you?

**Comment by Gillou68310** [comment]
Ok I pushed the fix for WDC and indi!

**Comment by fzurita** [comment]
Can this be merged now that you fixed Pokemon Puzzle league?

**Comment by Gillou68310** [comment]
I will double check that issue first

**Comment by gjimenezf** [comment]
Ready to close?

**Pull request closed without merging**
