### PR TITLE
Require SDL2

### PR DESCRIPTION
**Pull request by orbea**
Per https://github.com/mupen64plus/mupen64plus-core/pull/1093#issuecomment-2434092128 this should remove all checks and code required for SDL versions older than SDL 2.0.0.

### CODE REVIEW

**Comment by orbea** [comment]
@Rosalie241 I don't want to step on anyone's toes, but I had time to do this so I hope you don't mind. :)

**Comment by Rosalie241** [comment]
> @Rosalie241 I don't want to step on anyone's toes, but I had time to do this so I hope you don't mind. :)

That's fine, I've been busy with some of my other projects lately anyways so I didn't have the time to look into it yet, thanks for doing it for me :heart:

**Comment by Morilli** [comment]
Diff looks good. Should probably update the readme as well and remove the SDL 1.2 references from it.

**Comment by orbea** [comment]
> Diff looks good. Should probably update the readme as well and remove the SDL 1.2 references from it.

Done. I don't think I missed anything?

**Pull request merged**
