### PR TITLE
Allow game controllers to be unplugged and plugged in on the fly

### PR DESCRIPTION
**Pull request by fzurita**
This can be done using the controller plugin interface using the "Present" flag for each controller. I have to do more testing on it to make sure everything works correctly.

@bsmiles32 Can you review this and suggest improvements if necessary?

The main changes I did were to always initialize all controllers and use the controller API in pif.c to determine if a controller is present instead of checking for a null pointer for the controller interface.

I did a quick test using the smash brother player select screen and the hands were disappearing and appearing when the controller Present flag was toggled.

This is my attempt at fixing: https://github.com/mupen64plus/mupen64plus-core/issues/531

### CODE REVIEW

**Comment by bsmiles32** [comment]
Just quick notes for now (I'll try to submit some code later tonight) :
- I'd prefer if we regroup the controller presence and button state query to a single method eg

```
enum controller_input_error_code
{ NO_ERROR, NOT_PLUGGED }
enum controller_input_error_code controller_input_backend_interface.get_input(uint32_t* input)
```

This is simpler to implement for plugins and avoid incoherent state (controller present at presence check, but not at button polling).
- The joybus api shouldn't be changed. The controller presence check should be (re)done in the process_controller_command method.

**Comment by fzurita** [comment]
Yes, they was my initial approach, but I quickly discovered that process_controller_command did not seem to be intended to be called when a controller is not present. I guess, I could change that so it's always called.

**Comment by bsmiles32** [comment]
@fzurita Ok, pushed some modifications to make it work with the approach I proposed. Combined with https://github.com/mupen64plus/mupen64plus-input-sdl/pull/66, I am able to disconnect / reconnect a controller and see the select hand disappear/reappear. However a few gotcha's when reconnecting the controller (which looks related to the input plugin, not the core):
- there is some garbage data coming from the input driver just after reconnection.
- when testing with multiple controllers (eg. 3 controllers plugged, then unplug 1, then another, then replug the former, then the latter....) the input plugin gets confused about which controller maps which N64 controller

**Comment by fzurita** [comment]
Is that hot plug-in limitation of the sdl input plugin itself? The Android input plugin doesn't have such problem. I was able to hot plug without having the controllers connected at startup.

**Comment by bsmiles32** [comment]
I think it is a limitation of current sdl input plugin. Not sure if it is SDL itself or the input plugin with it's SDL1 heritage.

**Comment by fzurita** [comment]
@bsmiles32 I tested your changes against Android and everything works as well as my implementation. I'm able to start with controllers unplugged and then plugged them in on the fly, and the game will see them. Same goes with unplugging. Not to mention, it also fixes https://github.com/mupen64plus/mupen64plus-core/issues/528

**Comment by fzurita** [comment]
One thing I noticed though, in my implementation I made it so that ```channel->ijbd``` could never be null and I don't think you reverted that, but you put back the checks for ```channel->ijbd == NULL```

**Comment by bsmiles32** [comment]
You're right, ```channel->ijbd``` can't be NULL anymore because of how it is currently set up in main.c. However, I'll keep these tests for now in pif.c until I decide how I'll evolve the "device setup" part in main.c. Indeed, in some future work I'd like to add more flexibility regarding backends selection, and this work might make use of ijbd being NULL.

**Comment by fzurita** [comment]
Were there any N64 games that didn't support "hot-pluggin"?

**Comment by fzurita** [comment]
@richard42 can this be merged?

**Pull request merged**
