### PR TITLE
Improve 64DD emulation

### PR DESCRIPTION
**Pull request by LuigiBlood**
This adds two new interrupt handlers for the two different kinds of interrupts the 64DD can issue (MECHA and BM), then introduces delays based on clock speed (and CountPerOp, kinda to make sure), to every command, but especially the Seek command, and then changes the nature of BM interrupts to work with delays instead of working as fast as possible based on DMAs and other hacky reads.

The timing used is very approximate and is trying to be close to real hardware, but is not quite there, a lot more finetuning will be done eventually, but libleo is very tolerant.

This fixes Gnat Attack in Mario Artist Paint Studio prototype, as the game tries to read the next stage data before unloading the current stage, but since the 64DD responds way too quick it replaces the data before it actually unloads it and crashes.

### CODE REVIEW

**Comment by LuigiBlood** [comment]
I'll implement disk motor management next as it seems I did a bit of a regression in the process about Gnat Attack which just crashes the emulator again. This would fix it in a definitive manner.

**Comment by LuigiBlood** [comment]
The only change left for this is how many ticks is truly a second on mupen so I can properly manage that, perhaps..?

**Comment by richard42** [comment]
are you ready to merge this or is it WIP?

**Comment by LuigiBlood** [comment]
Yes this is usable I believe.

**Pull request merged**
