### PR TITLE
R4300 refactorings

### PR DESCRIPTION
**Pull request by bsmiles32**
This is a first step toward R4300 sub-module cleaning.
Main changes from this PR are:
- better decoupling of new_dynarec from old dynarec (for example, empty_dynarec is not needed anymore)
- better decoupling of dynarec / cached_interpreter (except for precomp_{block,inst} structures, cached_interp doesn't depends on dynarec)
- dynarec variables are now inside r4300.recomp, cached_interp inside r4300.cached_interp
- introduction of table based instruction decoder which is key this decoupling and should allow better maintenance of instruction decoding logic. In further work, I could possibly expand it's usage in pure_interpreter, and possibly streamline some more register/constants decodings.
- various cleanings

I've tested a bunch of games with no obvious regression (x64 dynarec, cached_interpreter), but I welcome other to test this, especially with new_dynarec and od 32 bit dynarec.

### CODE REVIEW

**Comment by Jj0YzL5nvJ** [comment]
For x64, when compiled using clang/clang++, this pull gives [a lot of warnings](https://0x0.st/sBzC.txt) (256)

```
$ clang --version
clang version 5.0.1-1~oibaf~x (tags/RELEASE_501/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bsmiles32** [comment]
@Jj0YzL5nvJ Thanks for testing and providing your feedback. The warnings should now be fixed.

I did a bit more testing performance-wise (time to render 1000 frames, no sound, nospeedlimit).[before/after in seconds]:
Mario Kart (dynarec): 20.8 / 19.5
CBFD (dynarec - cached interpreter): 31.3 / 30.7 - 38 / 37.8
GoldenEye (dynarec) : 13.2 / 13.2
F-Zero (dynarec) : 15.5 / 15.2
PerfectDark (dynarec - cached interpreter) : 17.9 / 17.9 - 21.5 / 22.0
WorldDriverChampionship (dynarec - cached interpreter) : 7.7 / 7.8 - 9.7 / 10.0
MajorasMask (dynarec) : 29.1 / 28.7

Performance is equivalent. But with a much more maintainable code base :)

**Comment by bsmiles32** [comment]
The new commit seems to also improve slightly the perf.
Mario Kart (dynarec - cached interpreter) [master/44b92.../01aec...] : 19.9/19.5/19.3 - 23.7/23.3/23.1

So pretty cool :)

**Comment by Jj0YzL5nvJ** [comment]
Maybe it's just my imagination, but using the dynamic recompiler (x64) in CBFD, when you start controlling Conker. On the way to the scarecrow, Conker speaks less (he complains less).

**Comment by fzurita** [comment]
Is this part of the refactoring?

```
  [armeabi-v7a] Compile arm    : mupen64plus-core <= ioapi.c
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/main/zip/ioapi.c:157:11: warning: implicit declaration of function 'ftello' is invalid in C99 [-Wimplicit-function-declaration]
      ret = FTELLO_FUNC((FILE *)stream);
            ^
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/main/zip/ioapi.c:20:29: note: expanded from macro 'FTELLO_FUNC'
  #define FTELLO_FUNC(stream) ftello(stream)
                              ^
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/main/zip/ioapi.c:203:8: warning: implicit declaration of function 'fseeko' is invalid in C99 [-Wimplicit-function-declaration]
      if(FSEEKO_FUNC((FILE *)stream, offset, fseek_origin) != 0)
         ^
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/main/zip/ioapi.c:21:45: note: expanded from macro 'FSEEKO_FUNC'
  #define FSEEKO_FUNC(stream, offset, origin) fseeko(stream, offset, origin)
                                              ^
```

**Comment by fzurita** [comment]
Some errors when building the new dynarec:

```
 In file included from /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/new_dynarec.c:1675:
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/arm/assem_arm.c:447:8: warning: initializing 'int *' with an expression of type 'u_int *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
    int *ptr=((u_int *)addr)+6;
         ^   ~~~~~~~~~~~~~~~~~
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/arm/assem_arm.c:4484:24: error: use of undeclared identifier 'cached_interpreter_table'
          emit_call((int)cached_interpreter_table.DDIV);
                         ^
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/arm/assem_arm.c:4512:24: error: use of undeclared identifier 'cached_interpreter_table'
          emit_call((int)cached_interpreter_table.DDIVU);
                         ^
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/new_dynarec.c:2213:67: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
        if((start!=0)&&(page<2048)&&((start-(u_int)g_dev.rdram.dram)>=0)&&((end-(u_int)g_dev.rdram.dram)<0x800000)) {
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ ~
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/new_dynarec.c:10840:35: warning: passing 'u_char *' (aka 'unsigned char *') to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    __clear_cache((void *)beginning,out);
                                    ^~~
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/arm/assem_arm.h:46:46: note: passing argument to parameter 'end' here
  void __clear_cache_bugfix(char* begin, char *end);
```

**Comment by fzurita** [comment]
After I fix the two errors I get:
```
  [armeabi-v7a] SharedLibrary  : libmupen64plus-core.so
  /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/arm/linkage_arm.o(.text+0x19c): error: undefined reference to 'dynarec_gen_interrupt'
```

**Comment by fzurita** [comment]
I fixed the above error by adding this to assem_arm.c

```
void dynarec_gen_interrupt(void)
{
    gen_interrupt(&g_dev.r4300);
}
```

Now the new dynarec is crashing at startup.

**Comment by fzurita** [comment]
Here is the crash:
```
********** Crash dump: **********
Build fingerprint: 'razer/cheryl/cheryl:7.1.1/NMF26X-RZR-180118/3005:user/release-keys'
pid: 11514, tid: 11543, name: ServiceStartArg  >>> paulscode.android.mupen64plusae.GameActivity <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xca6fc9f6
Stack frame #00 pc 0001cda8 ./libmupen64plus-core.so: Routine savestates_load_m64p at ./src/main/savestates.c:539
Stack frame #01 pc 000b4aec  /data/app/org.mupen64plusae.v3.alpha-2/lib/arm/libmupen64plus-core.so: Routine .E1 at linkage_arm.S:?
```

**Comment by fzurita** [comment]
Looks  like you undid this accidentally:

https://github.com/mupen64plus/mupen64plus-core/pull/545

**Comment by fzurita** [comment]
After fixing all that, it seems to run ok.

**Comment by fzurita** [comment]
Performance seems identical in the new dynarec in ARM.

**Comment by bsmiles32** [comment]
@fzurita Thanks for your tests. I pushed some fixes you reported. I don't know why you got the savestate regression though.

**Comment by fzurita** [comment]
Well, I got the save state regression because it seems that you don't have #545 in your user branch.

**Comment by bsmiles32** [comment]
Indeed, was not up-to-date with upstream. I've rebased against latest master now.

@richard42 : I'll let you decide if you want it to be part of the incoming release or not. But looking at the feedback, it should be in mergeable state now.

**Comment by fzurita** [comment]
Could a branch be made for a release? That way the master branch doesn't miss a beat and the release branch can happen at any revision.

**Pull request merged**
