### PR TITLE
new_dynarec fixes

### PR DESCRIPTION
**Pull request by Gillou68310**

### CODE REVIEW

**Comment by fzurita** [comment]
This allows clang to build in Android, thanks!

**Comment by fzurita** [comment]
I'm getting crashes with this when trying to stop the core

```
********** Crash dump: **********
30896-30896/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'razer/cheryl/cheryl:8.1.0/OPM1.171019.011-RZR-180803/6033:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 30846, tid: 30873, name: ServiceStartArg  >>> paulscode.android.mupen64plusae.GameActivity <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7aab21edc8
    x0   000000000001ee00  x1   0000000000000200  x2   0000007bab200000  x3   0000007babfc0688
    x4   0000007babfc0648  x5   0000007babfc0688  x6   000000000465ca38  x7   000000000465ca58
    x8   0000000000000007  x9   ab0b69c5fb7a2d04  x10  ab0b69c5fb7a2d04  x11  0000000000000011
    x12  0000000000000002  x13  0000007c45118300  x14  0000007bab102588  x15  0000007c4513e8a8
    x16  0000007bab200088  x17  0000000000000008  x18  000000000000003b  x19  0000007aab21edc0
    x20  0000007bab102588  x21  0000007ba7238000  x22  00000000fffffffc  x23  0000007aab21edc0
    x24  0000007b02a00000  x25  0000007ba723b000  x26  0000007baab3ea68  x27  0000007ba2d186d8
    x28  0000007baab3e8c8  x29  0000007baab3e000  x30  0000007ba2cc6500
    sp   0000007bab0f5f20  pc   0000007ba2cc64a8  pstate 0000000060000000


#00 0x00000000000864a8 libmupen64plus-core.so
emit_extjump2
/src/device/r4300/new_dynarec/arm64/assem_arm64.c:0:10
#01 0x000000000001be44 libmupen64plus-core.so
event_sdl_filter
/src/main/eventloop.c:0:25
#02 0x0000000000012100 libmupen64plus-core.so (CoreDoCommand+1132)
                                                                                                                         zipWriteInFileInZip
                                                                                                                         /subprojects/minizip/zip.c:1491:56
#03 0x0000000000005c28 libmupen64plus-ui-console.so (SDL_main+13516)
#04 0x0000000000010684 /data/app/org.mupen64plusae.v3.fzurita-stHn9GHHGS4SmjKxbEVPAw==/oat/arm64/base.odex (offset 0x10000)
Crash dump is completed
```

**Comment by Gillou68310** [comment]
Do you know which commit introduced the crash?

**Comment by fzurita** [comment]
I'll check

**Comment by fzurita** [comment]
It was this commit: 4cbf149a7e324f02cb6fc3ddce81b8a7ce066c79

**Comment by Gillou68310** [comment]
Thanks I'll check

**Comment by Gillou68310** [comment]
I cannot reproduce this issue on my odroid. Do you have more infos on how to reproduce this issue? Is it random?

**Comment by fzurita** [comment]
It happens to me 100% of the time when commanding the core to stop.

**Comment by Gillou68310** [comment]
weird

**Comment by fzurita** [comment]
Have you tried compiling with clang?

**Comment by Gillou68310** [comment]
arm64? arm32? both?

**Comment by Gillou68310** [comment]
I'm crosscompiling for my odroid, I don't have a clang toolchain.

**Comment by fzurita** [comment]
I have only tested arm64, I'll try arm32 when I get a chance.

**Comment by fzurita** [comment]
I have this code in the google play store and I'm hearing of some reports of paper mario crashing after loading an in-game save. I'm trying to get an in-game save to go with it.

**Comment by fzurita** [comment]
32 bit arm is not crash on Stop

**Comment by fzurita** [comment]
Actually, the paper Mario crash is easy to reproduce, start a new game, it will crash when Mario leaves his house

**Comment by Gillou68310** [comment]
Could you check that base_addr_rx==base_addr

**Comment by fzurita** [comment]
```
E/Core: based_addr=0x0x7ba745a000 based_addr_rx=0x0x7ba745a000
```

**Comment by Gillou68310** [comment]
Do you have asserts enable?

**Comment by fzurita** [comment]
Nope, but I can enable them.

**Comment by Gillou68310** [comment]
Yes please! I just want to be sure no assert is triggered.

**Comment by Gillou68310** [comment]
I managed to reproduce the paper mario crash BTW, I will investigate the issue thanks for reporting

**Comment by fzurita** [comment]
Yep, got an assert on stop:
```
A/libc: /home/fzurita/git_projects/mupen64plus/mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/new_dynarec/new_dynarec.c:7713: void new_dynarec_cleanup(void): assertion "copy_size==0" failed
```

**Comment by fzurita** [comment]
Never mind, I'm just mis-reading the code....

**Comment by fzurita** [comment]
Yeah, the assert happens even with DISABLE_BLOCK_LINKING set to 1.

**Comment by fzurita** [comment]
Why wouldn't ```ll_clear``` always leave ```copy_size``` equal to zero?

**Comment by Gillou68310** [comment]
If it fails to free all dynamically allocated copy of original source code:
```
  copy=NULL;
  copy=(char*)malloc((slen*4)+4);
  assert(copy);
  copy_size+=((slen*4)+4);
```

which means it probably failed to get the correct address from get_copy_addr.
What I don't understand is why I cannot reproduce the issue.

Could you tell me which condition is taken:
```
  //copy
  offset=(((intptr_t)copy&~0xfffLL)-((intptr_t)out_rx&~0xfffLL));
  if((uintptr_t)copy<4294967296LL){
    emit_movz_lsl16(((uintptr_t)copy>>16)&0xffff,2);
    emit_movk(((uintptr_t)copy)&0xffff,2);
  }else if(offset>=-4294967296LL&&offset<4294967296LL){
    emit_adrp((intptr_t)copy,2);
    emit_addimm64(2,((intptr_t)copy&0xfffLL),2);
  }else{
    emit_loadlp((intptr_t)copy,2);
  }
```

**Comment by fzurita** [comment]
Ok, I feel silly now, I'm misunderstood how assert works... it will abort if the given condition is not true, not the other way around....

**Comment by Gillou68310** [comment]
lol don't worry we're all tired during the weekend ;-)

**Comment by fzurita** [comment]
There are two instances of that code in assem_arm64.c. In Mario 64, it's always the first instance of that code, and it's this condition ```}else if(offset>=-4294967296LL&&offset<4294967296LL)```

**Comment by Gillou68310** [comment]
Ok thanks I will check

**Comment by fzurita** [comment]
If you want to try this yourself, all you need is a 64 bit android device and a PC with Android Studio 3.3.

The offending code is all checked in here: https://github.com/mupen64plus-ae/mupen64plus-ae/commits/master

To enable asserts, change this from ```release``` to ```debug```

and delete this code to reproduce the issue:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/65de6d32a37a4d7455c4770b666a4fed843d6b38/app/src/main/java/paulscode/android/mupen64plusae/jni/CoreService.java#L166-L170

**Comment by Gillou68310** [comment]
@fzurita I pushed a fix for Paper mario. Could you check it?

**Comment by fzurita** [comment]
Yep!

**Comment by Gillou68310** [comment]
Also a possible fix for the crash at exit. How did I not see this before!!!!

**Comment by fzurita** [comment]
Paper Mario crash fixed! Crash on stop fixed!

**Comment by Gillou68310** [comment]
Good to hear! Thanks for testing.

**Comment by Gillou68310** [comment]
BTW without https://github.com/mupen64plus/mupen64plus-core/pull/606/commits/c43dabcfb0aed9624bbd3887187ebbb528594d31 crash can also occur when reaching the end of the dynarec buffer. Banjo-tooie is a known candidate to reach the end of the buffer really quickly. So if you got reports of Banjo-tooie crashing this might also fix the issue.

**Comment by fzurita** [comment]
Ok, thanks for the heads up!

**Comment by fzurita** [comment]
@Gillou68310 are you going to include the performance fixes as part of this pull request?

**Comment by Gillou68310** [comment]
yep, I still have a few things to clean up before committing

**Comment by fzurita** [comment]
After all these fixes, I'm getting some reports of Pokemon Stadium 2 (U) crashing when starting a battle. I can't seem to reproduce it though.

Allegedly, it's happening when starting the game and using the "Battle Now" option.

**Comment by Gillou68310** [comment]
Could you check if this is a regression, or if it was already there before my commits?

**Comment by fzurita** [comment]
This game used to work ok work the 32bit arm new dynarec. So it's a new issue. Not sure yet if from the original 64bit pull request or this one.

I can try to bisect which commit broke it if you wish, but it will have to wait until at least 12 hours from now.

**Comment by Gillou68310** [comment]
Please yes it will save me a lot of time. Take your time BTW

**Comment by fzurita** [comment]
It looks like this commit broke 32 bit arm dynarec:

https://github.com/mupen64plus/mupen64plus-core/commit/9525ed42cede1d9ab1fec91b57d78d3fd8fc8f9a

**Comment by Gillou68310** [comment]
Thanks I'll investigate

**Comment by fzurita** [comment]
Smash brothers is also crashing when selecting VS mode option with 32bit arm new dynarec. Probably same issue.

**Comment by fzurita** [comment]
I do notice a small discrepancy between assem_arm.c and assem_arm64.c. In assem_arm64.c, you have a check for ```addr==0``` in ```emit_writehword_indexed_tlb```. You don't have that same check in assem_arm.c.

**Comment by fzurita** [comment]
Another issue, this is a game that used to work as well. Pokemon Puzzle league seems to crash with the 64 bit arm dynarec. It's easy to reproduce, start the game and select puzzle University and try to start a puzzle as a guest.

I was able to recreate the crash one time with the 32 bit arm dynarec, but it seems to happen much more rarely.

**Comment by Gillou68310** [comment]
@fzurita I pushed a fix for storelr, could you check it?

> Another issue, this is a game that used to work as well. Pokemon Puzzle league seems to crash with the 64 bit arm dynarec. It's easy to reproduce, start the game and select puzzle University and try to start a puzzle as a guest.

The game doesn't even boot for me! When you say it used to work well, when was that?

**Comment by fzurita** [comment]
It boots ok right now, at least in Android. Only the 64bit arm dynarec has real issues. What's the md5 of your ROM?

**Comment by Gillou68310** [comment]
E722576A15182CFED6782379CE4BC8BE

**Comment by loganmc10** [comment]
I ran into an issue a long time ago with the new dynarec and PPL, I don't think it was ever resolved:

https://github.com/mupen64plus/mupen64plus-core/issues/304

**Comment by Gillou68310** [comment]
lol totally forget about this one, thanks @loganmc10 it's indeed the same issue on arm64, at least for my ROM

**Comment by fzurita** [comment]
@Gillou68310 that matches the md5 of my ROM. I wonder why it behaves differently? Compiler maybe?

**Comment by Gillou68310** [comment]
You're testing release mode?

**Comment by fzurita** [comment]
Oh... I have assets disabled by default on my build. That's probably why is "working".

**Comment by Gillou68310** [comment]
yeah

**Comment by Gillou68310** [comment]
Ok since it's not regression I will deal with this later

**Comment by fzurita** [comment]
Pokemon Stadium 2 and smash brothers are both fixed with the last commit.

**Comment by Gillou68310** [comment]
Cool

**Comment by Gillou68310** [comment]
Ready to merge

**Comment by fzurita** [comment]
Huh oh, something changed. I'm getting reports that Mario Tennis (U) is no longer booting. I tried it, and I can confirm, it doesn't crash, but it does hang before any frames are displayed. I can try to track down which commit broke it later.

**Comment by Gillou68310** [comment]
Ok don't waste your time this is still caused by https://github.com/mupen64plus/mupen64plus-core/commit/9525ed42cede1d9ab1fec91b57d78d3fd8fc8f9a. I'll investigate further tomorrow.

**Comment by fzurita** [comment]
Ok

**Comment by fzurita** [comment]
@Gillou68310 with all the fixes you have done, the number of core dumps being reported has reduced drastically. I'm still seeing two core dumps being reported though, I can't tell if they are new since line number have changed for everything:

```
********** Crash dump: **********
#00 0x0000000000086948 ./libmupen64plus-core.so
   dma_sp_write
   ./device/rcp/rsp/rsp_core.c:58:33
   write_rsp_regs
   ./device/rcp/rsp/rsp_core.c:235:0
#01 0x000000000004d7c0 ./libmupen64plus-core.so
   mem_write32
   ./device/memory/memory.h:87:5
   r4300_write_aligned_word
   ./device/r4300/r4300_core.c:353:0
#02 0x0000000000080e84 ./libmupen64plus-core.so
   write_word_new
   ./device/r4300/new_dynarec/new_dynarec.c:11279:3
#03 0x0000000000122098 <anonymous>
Crash dump is completed
```
```
********** Crash dump: **********
#00 0x00000000000a7e48 ./libmupen64plus-core.so
   read_rdram_dram_corrupted
   ./device/rdram/rdram.c:90:14
#01 0x00000000000a10bc ./libmupen64plus-core.so
   mem_read32
   ./device/memory/memory.h:82:5
   r4300_read_aligned_word
   ./device/r4300/r4300_core.c:298:0
   read_byte_new
   ./device/r4300/new_dynarec/new_dynarec.c:11194:0
#02 0x0000000000037eb0 <anonymous>
Crash dump is completed
```
The core dumps are against this revision: 85c16305942be6790c76006ebe89a5bd91f465fb
Plus this patch applied: https://github.com/fzurita/mupen64plus-ae/commit/01e076c8b6342da4b3ecb2ca6e2e41bfb4f5bc6b

**Comment by fzurita** [comment]
For the 2nd core dump, I could see a crash happening since this is the size of RDRAM:
```
rdram_size = (disable_extra_mem == 0) ? 0x800000 : 0x400000;
```

But in ```read_rdram_dram_corrupted``` where the crash happens the function ```rdram_dram_address``` only has this protection for addresses:
```
return (address & 0xffffff) >> 2;
```

So, I could see us going past the end of the ```dram``` array size.

**Comment by fzurita** [comment]
Similar issue in the first core dump,```sp->mem``` array, we can go past the end of array there as well.

**Comment by fzurita** [comment]
@Gillou68310 Here is a crazy idea. Have the new dynarec output code to LLVM IR instead of a specific architecture. Then we can have LLVM have an optimization pass on the generated code and have LLVM output to the right architecture.

**Comment by fzurita** [comment]
Lol, yeah, from a maintainability standpoint LLVM IR would be better. But you are right, you did all this work already for all the different architectures.

**Comment by fzurita** [comment]
Nice! I'll check it out

**Comment by Gillou68310** [comment]
Concerning the core dump, as usual I won't be able to investigate on it without being able to reproduce the issue, sorry.

**Comment by Gillou68310** [comment]
But good to hear the number of core dump reduced!

**Comment by fzurita** [comment]
Mario Tennis is not quiet working. I'm getting a core dump now.

**Comment by Gillou68310** [comment]
Could you share it? arm64 or arm32?

**Comment by fzurita** [comment]
Back trace is not very useful:
```
2019-01-29 09:00:54.205 30088-30088/? I/crash_dump64: performing dump of process 30048 (target tid = 30075)
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG: Build fingerprint: 'razer/cheryl/cheryl:8.1.0/OPM1.171019.011-RZR-180803/6033:user/release-keys'
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG: Revision: '0'
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG: ABI: 'arm64'
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG: pid: 30048, tid: 30075, name: ServiceStartArg  >>> paulscode.android.mupen64plusae.GameActivity <<<
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x100000004
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x0   000000734932f0e0  x1   00000000a0100000  x2   0000000000000001  x3   0000000000000001
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x4   0000000000800000  x5   00000000803fefe8  x6   0000000080300355  x7   0000000080300064
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x8   00000000a0100000  x9   0000000080031000  x10  00000000ffffffff  x11  00000000ffffffff
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x12  000000008c422ba0  x13  000000003c028003  x14  000000008c422ba0  x15  00000000038c422b
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x16  0000000100000000  x17  0000000080031000  x18  000000000000002f  x19  0000000000000000
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x20  0000000000c0bcee  x21  00000000a40002f4  x22  0000000000000000  x23  0000000000000001
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x24  0000000000000000  x25  00000000ffffffff  x26  00000000ffffffff  x27  0000000000000000
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     x28  0000000000000000  x29  000000734bc30000  x30  0000007349c38c74
2019-01-29 09:00:54.205 30088-30088/? A/DEBUG:     sp   000000734d1fd390  pc   0000007349c38d24  pstate 0000000040000000
2019-01-29 09:00:54.206 30088-30088/? A/DEBUG: backtrace:
2019-01-29 09:00:54.207 30088-30088/? A/DEBUG:     #00 pc 0000000000008d24  <anonymous:0000007349c30000>
2019-01-29 09:00:54.207 30088-30088/? A/DEBUG:     #01 pc 0000000000008c70  <anonymous:0000007349c30000>

Crash dump is completed

```

**Comment by fzurita** [comment]
arm64

**Comment by fzurita** [comment]
32 bit doesn't crash.

**Comment by Gillou68310** [comment]
Where does it crash?

**Comment by fzurita** [comment]
Before it even shows a single frame.

**Comment by Gillou68310** [comment]
Weird, it works on my odroid

**Comment by fzurita** [comment]
I'll turn on asserts, maybe it will show something.

**Comment by fzurita** [comment]
Yeah, very repeatable. Turning on optimization makes it crash, without optimization, it doesn't crash.

**Comment by Gillou68310** [comment]
Lol yeah ```assert(genimm((uint64_t)imm,64,&armval));``` in emit_andimm64

**Comment by fzurita** [comment]
Whoops, lol

**Comment by fzurita** [comment]
Ok, I can confirm, no more crash after getting that code out of the assert.

**Comment by fzurita** [comment]
This is a weird one. I'm getting some new crash reports with bad back traces with these signals:

```signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)```

**Comment by Gillou68310** [comment]
Yeah probably brk 0 instruction from linkage_arm64.S. Are you able to reproduce it?

**Comment by Gillou68310** [comment]
BTW I did some work on block linking https://github.com/Gillou68310/mupen64plus-core/tree/block_linking
Could you test it when you got time?

**Comment by fzurita** [comment]
Oh, and yeah, sure, I'll check that branch out.

**Comment by Gillou68310** [comment]
What would it need to have at least the game name?

**Comment by Gillou68310** [comment]
Are we sure they are using the latest version BTW?

**Comment by fzurita** [comment]
They were running at least this revision: 06669827f959b58d33360383d7f111c3a34637a1 but before you rebased it. I fixed the assert issue myself and put it in the google play store.

**Comment by Gillou68310** [comment]
ok

**Comment by fzurita** [comment]
I did a test with a few games with your block_linking branch and it seems to run.

**Comment by Gillou68310** [comment]
Ok do you see any perf impact?

**Comment by fzurita** [comment]
Performance seems mostly identical. Maybe a 1% improvement, but it's in the noise.

**Comment by Gillou68310** [comment]
Ok thanks for testing

**Comment by fzurita** [comment]
I'm also seeing some "illegal opcode" crashes on this line of code:
```
./src/device/r4300/new_dynarec/arm64/linkage_arm64.S:197:0
```

**Comment by fzurita** [comment]
Well, this is the cause for the illegal opcode: https://www.google.com/amp/s/www.theregister.co.uk/AMP/2016/09/13/arm_biglittle_gcc_bug/

Buggy samsung CPUs, these illegal instruction core dumps seem to be only happening with Exynos CPUs, specially Galaxy S7.

**Comment by fzurita** [comment]
Seems like an easy fix: https://github.com/dolphin-emu/dolphin/pull/4204/files

**Pull request merged**
