### PR TITLE
Preliminary memory refactorings

### PR DESCRIPTION
**Pull request by bsmiles32**
This PR extracts non problematic commits from the previous PR (#47).
It mostly consists in preliminary work for the memory subsystem refactoring:
-simple cleanings
-less duplication for memory handlers
-rewrite breakpoints checks on memory access
-some work toward elimination of direct global variable usage

Edit: Note as per @littleguy77 request I fixed the rdram -> g_rdram commit and rebased against master.

### CODE REVIEW

**Comment by Narann** [comment]
I will test this asap.

**Comment by littleguy77** [comment]
Me too, probably within the next few hours.

**Comment by littleguy77** [comment]
No issues on Windows (MSVC 2010) or Android (mupen64plus-ae).  Looks great :+1:

**Comment by Narann** [comment]
Good on my side. I would wait for @Gillou68310 greenlight (if he want to test) and I will merge. :)

**Comment by Gillou68310** [comment]
Good for me too ;-)

**Comment by Gillou68310** [comment]
Damn I should have tested before before speaking, this breaks compilation on MSVC here's the log:
```
1>  dma.c
1>  debugger.c
1>  dbg_memory.c
1>  \mupen64plus-core\src\debugger\dbg_memory.c(283): warning C4013: 'get_memory_type' undefined; assuming extern returning int
1>  dbg_decoder.c
1>  dbg_breakpoints.c
1>  \mupen64plus-core\src\debugger\dbg_breakpoints.c(78): warning C4013: 'activate_memory_break_read' undefined; assuming extern returning int
1>  \mupen64plus-core\src\debugger\dbg_breakpoints.c(84): warning C4013: 'activate_memory_break_write' undefined; assuming extern returning int
1>  \mupen64plus-core\src\debugger\dbg_breakpoints.c(100): warning C4013: 'deactivate_memory_break_read' undefined; assuming extern returning int
1>  \mupen64plus-core\src\debugger\dbg_breakpoints.c(106): warning C4013: 'deactivate_memory_break_write' undefined; assuming extern returning int
1>  cp1.c
1>  cp0.c
1>  config.c
1>  common.c
1>  cheat.c
1>  callbacks.c
1>  cached_interp.c
1>  assemble.c
1>  Generating Code...
1>  debugger.c
1>  screenshot.cpp
1>  osd.cpp
1>  OGLFT.cpp
1>  Generating Code...
1>Link:
1>dbg_breakpoints.obj : error LNK2019: unresolved external symbol _activate_memory_break_write referenced in function _enable_breakpoint
1>dbg_breakpoints.obj : error LNK2019: unresolved external symbol _activate_memory_break_read referenced in function _enable_breakpoint
1>dbg_breakpoints.obj : error LNK2019: unresolved external symbol _deactivate_memory_break_write referenced in function _disable_breakpoint
1>dbg_breakpoints.obj : error LNK2019: unresolved external symbol _deactivate_memory_break_read referenced in function _disable_breakpoint
1>dbg_memory.obj : error LNK2019: unresolved external symbol _get_memory_type referenced in function _read_memory_32

```

**Comment by bsmiles32** [comment]
These debugging functions need the DBG macro to be defined in order to be generated.

**Comment by Gillou68310** [comment]
Sure but they shouldn't be used when the DBG macro isn't defined.

Such things cannot be done on MSVC:
```
ifeq ($(DEBUGGER), 1)
  CFLAGS += -DDBG
endif

ifeq ($(DEBUGGER), 1)
  SOURCE += \
	$(SRCDIR)/debugger/debugger.c \
	$(SRCDIR)/debugger/dbg_decoder.c \
	$(SRCDIR)/debugger/dbg_memory.c \
	$(SRCDIR)/debugger/dbg_breakpoints.c
  LDLIBS += -lopcodes -lbfd
endif
```
This means that the previous source files are always part of the compilation.

**Comment by littleguy77** [comment]
Can't this be addressed the same way you addressed the NEW_DYNAREC builds in MSVC?  I.e. create a new build configuration and exclude some of the source/library files?
http://msdn.microsoft.com/en-us/library/ms171455(v=vs.100).aspx

**Comment by Gillou68310** [comment]
Sure it can, but IMO I don't think it's a good idea to have tons of build configurations ;-)

**Comment by littleguy77** [comment]
Me neither (MSVC build management sucks).  But it sounds like you don't intend to use -DDBG, correct?  In that case don't include it by default.  If an MSVC user wants it, they can create their own (new) build config.  Correct me if I'm oversimplifying or missing something.

**Comment by Gillou68310** [comment]
> In that case don't include it by default

You mean exclude the following files files by default? 
debugger/debugger.c \
debugger/dbg_decoder.c \
debugger/dbg_memory.c \
debugger/dbg_breakpoints.c

**Pull request merged**
