### PR TITLE
Set VSync (SDL_GL_SetSwapInterval) after GL context is available

### PR DESCRIPTION
**Pull request by dankcushions**
This fixes https://github.com/mupen64plus/mupen64plus-core/issues/663

In my case, before this fix VSync was always ON in linux and standalone commandline (`--noosd`) mupen64plus.

### CODE REVIEW

**Comment by dankcushions** [comment]
the sdl 2 ifdefs are wrong now. will fix soon!

**Comment by dankcushions** [comment]
Building properly on non-SDL 2.0.0. now. Good to go!

**Comment by dankcushions** [comment]
Anything I can do to get this over the line? Seems to have gone a little quiet around here :eyes:

**Comment by psyke83** [comment]
This appears to break mupen64plus on RPI4 when launched via an Xorg context. No window will appear, and In the log, I see `Core Error: SDL swap interval (VSync) set failed: That operation is not supported`, followed by an application hang.

It's late here, so I'll try to provide more detail after I've had more time to check it out. Presumably the solution is to omit the `return M64ERR_SYSTEM_FAIL;` entirely when the swap interval is not successfully changed, as it shouldn't be a fatal error. I'm not certain why the function is failing in the first place, though.

**Comment by psyke83** [comment]
Please disregard my last post - apologies. I didn't notice that my Xorg session was using the llvmpipe software driver, which doesn't support setting the swap interval. After fixing that, the PR works fine, and fixes vsync with both the `kmsdrm` and `x11` SDL2 drivers.

Without this PR, `SDL_GL_SetSwapInterval` returns the `No OpenGL context has been made current` SDL [https://github.com/spurious/SDL-mirror/blob/master/src/video/SDL_video.c#L3586](error). In a case such as this, the swap interval will depend on whatever default the internal driver sets... `x11` and `rpi` is either `1` or `-1` (adaptive sync), and `kmsdrm` defaults to `0`. So this change is highly recommended to guarantee the user setting is applied correctly.

**Comment by Gillou68310** [comment]
@dankcushions I want to merge this, could you rebase and squash to one commit?

**Comment by dankcushions** [comment]
@Gillou68310 done!

**Comment by Gillou68310** [comment]
thanks

**Pull request merged**
