### PR TITLE
Fixes for last save state update

### PR DESCRIPTION
**Pull request by fzurita**
Minor cleanup from last pull request. This disables Speculative recompilation when loading pj64 save states.

### CODE REVIEW

**Comment by fzurita** [comment]
I made some more corrections. The additional stop_after_jal data was not being stored in the correct place.  Because of that, the correct value was also not being read.

I did a quick test of writing a random value for the ```stop_after_jal``` flag and the same value was correctly read back.

In addition, we seem to be relying on ```unsigned int``` being 32 bits and ```short``` being 16 bits, which is not guaranteed by the C standard. So potentially, a save state created in one platform may not be compatible in another platform. I don't think this is the problem with not being able to load ```NEW_DYNAREC``` save states on build without ```NEW_DYNAREC```.

**Comment by fzurita** [comment]
@richard42 can you review and make comments or merge?

**Comment by richard42** [comment]
yep, looks good to me.

**Comment by fzurita** [comment]
Thanks!

**Pull request merged**
