### PR TITLE
Create files_macos.c

### PR DESCRIPTION
**Pull request by StenApp**
First try to get a proper Mupen64Plus app on macOS

### CODE REVIEW

**Comment by StenApp** [comment]
Doesn't work completely,  `CFCopyHomeDirectoryURL()` is iOS only...

**Comment by richard42** [comment]
looks pretty good. I can't merge this until the ios-only function is fixed though

**Comment by StenApp** [comment]
Looking on how to get the path anyhow.

**Comment by StenApp** [comment]
Grrrrrrrr!

save folder goes to ApplicTsave in user Library instead of created folder /Users/currentuser/Library/ApplicationSupport/Mupen64Plus/save

need help!

**Comment by richard42** [comment]
this change looks okay. You might also want to check that getenv("HOME") returns a non-NULL pointer, initialize the path[] array to an empty string, and keep the fallback to the getpwuid() function, with something like this:
`    if (strlen(path) == 0)
    {
        struct passwd* pwd = getpwuid(getuid());
        if (pwd)
            strcpy(path, pwd->pw_dir);
    }`

**Pull request merged**
