### PR TITLE
Fix issues listed in #385

### PR DESCRIPTION
**Pull request by Gillou68310**

### CODE REVIEW

**Comment by loganmc10** [comment]
You've got a build failure in AppVeyor

**Comment by Gillou68310** [comment]
Yeah I saw but I don't understand how it's related to my commits.

**Comment by Gillou68310** [comment]
I just check on my computer and it build just fine for x64

**Comment by fzurita** [comment]
This is the error:
```
Performing Custom Build Tools
  C:\projects\mupen64plus-core\src\device\r4300\x86_64\dyna_start.asm:21: fatal: unable to open include file `asm_defines_nasm.h'
```

Skins unrelated to anything you did

**Comment by loganmc10** [comment]
Yeah it probably just crapped out, I can restart Travis builds but I don't think I have permission to restart AppVeyor builds

**Comment by fzurita** [comment]
All games are booting now except for dance dance revolution. Dance dance revolution was booting until recently.

**Comment by Gillou68310** [comment]
Thanks for testing! Could you bisect which commit broke dance dance revolution?

**Comment by fzurita** [comment]
Yeah, I can check.

**Comment by Gillou68310** [comment]
Thanks ;-)

**Comment by fzurita** [comment]
For reference, the DDR game does boot with interpreter and the old dynarec.

**Comment by fzurita** [comment]
It was the rework of TLB exceptions that broke the Dance Dance Revolution game in the new dynarec.

**Comment by fzurita** [comment]
It looks like South Park 64 is also broken. This pull request doesn't fix it.

**Comment by fzurita** [comment]
@richard42 was it to early to merge this? This did fix a few of the mentioned games, but it broke others.

**Comment by richard42** [comment]
oops. did this one break DDR? I was under the impression that this didn't fix everything but didn't break anything either.

**Comment by fzurita** [comment]
See the commentary in #385.

**Comment by richard42** [comment]
Well it looks like this PR fixed the new dynarec problems for most of the games that were broken by recent changes, except DDR and South Park. But it caused a crash in Banjo Kazooie? Let's just open a new issue and keep moving forward.

**Pull request merged**
