### PR TITLE
CI/CD: Rearranged some parts of the logic, many details and more...

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
@Rosalie241

### CODE REVIEW

**Comment by richard42** [comment]
is it ready?

**Comment by Jj0YzL5nvJ** [comment]
> is it ready?

In theory yes, but better to wait until Monday. If during that period I don't change anything else, you can assume it's ready.
I will try to test this code in my repositories during that period, but I don't have as much free time as I would like.

**Comment by Jj0YzL5nvJ** [comment]
I will make more changes, I accidentally added unnecessary variables that I used in mupen64plus/mupen64plus-video-glide64mk2#131 diagnostic.

**Comment by Jj0YzL5nvJ** [comment]
Now it's ready, unless someone has something else to point out.

**Pull request merged**
