### PR TITLE
Cenification part1

### PR DESCRIPTION
**Pull request by bsmiles32**
This PR provides better modularization of n64 core components.
It is largely inspired by the work of MarathonMan for his cycle accurate emulator CEN64.

With the new modularization, several new subsystems have been introduced:
-AI (Audio Interface) : it contains for now only the audio interface controller.
-PI (Parallel Interface): it contains the parallel interface controller, the cart rom, the flashram and sram modules.
-RI (RDRAM Interface): it contains the RDRAM interface controller, and the RDRAM module.
-SI (Serial Interface): it contains the serial interface controller, the PIF, the game controllers, mempaks, the cart CIC, cart EEPROM and cart AF-RTC.
-VI (Video Interface): it contains for now only the video interface controller.
-RSP: it contains only the RSP core module.
-RDP: it contains the RDP core module and the FrameBuffers monitoring informations.
-R4300: it contains the R4300 core module, the MIPS interface controller, and everything that was already present before.

All new modules avoid heavy usage of global variables except when no other option was possible (plugin, stuff for instance).

With this PR, I tried not to refactor too much the individual modules in order to prevent accidental behavior changes. Individual refactorings will come later.
I have also avoided heavy refactorings within the R4300 subsystem because it would very likely break the NEW_DYNAREC. This will also be addressed in a subsequent PR.

### CODE REVIEW

**Comment by littleguy77** [comment]
Looks fine on Android :+1:

**Comment by Narann** [comment]
Wow! I'm very impressed by the result. The new organization look less confusing than before! Amazing work! I will let @richard42 merge.

**Comment by bsmiles32** [comment]
Thanks for the kind word. I have unfortunately bad news. My 6 year old laptop has stopped to work. So until I fix/replace it I won't be able to contribute more. Plus there is a chance that all my data are lost. :(

**Comment by littleguy77** [comment]
Bummer. :cry:  Hope you can recover your data.

**Comment by Narann** [comment]
Arf! I hope you will be able to get your datas back!

**Comment by bsmiles32** [comment]
@richard42 : No love for my PR ? :)
More seriously, do you need more time to review it or is there anything blocking ?

**Comment by Narann** [comment]
I would push it actually, but as you had some troubles with your hardware, I was waiting you to have a dev env again in case some big stuff would break elsewhere and you could not help to fix. Is your dev env back? :)

**Comment by richard42** [comment]
Sorry bsmiles32, my grandmother passed away recently and I was gone all last week for her funeral.  I haven't had time to review this major change yet.  There are a ton of changes here and I'd like to look through it a bit before merging.  I haven't forgotten; it's still in my inbox.

**Comment by bsmiles32** [comment]
@richard42 : I'm sorry for your loss. Take your time to review this PR.

**Comment by Narann** [comment]
@richard42 : Sorry for your loss. :( We will wait for your reviews.

**Pull request merged**
