### PR TITLE
Added GoldenEye X and Perfect Dark Plus to INI

### PR DESCRIPTION
**Pull request by Graslu**
GoldenEye X and Perfect Dark Plus entries added to mupen64plus.ini

### CODE REVIEW

**Comment by loganmc10** [comment]
For the ```Alternate Title``` field, you can't put arbitrary fields in the INI, or the Core will report this error:

```
Core Warning: ROM Database: Unknown property on line 5932
```

You can add comments though, any line starting with a ```;``` is a comment, so I would do:

```
[67F2E18ED18A5F0EA3FE2D913E3F1786]
GoodName=GoldenEye X
; Alternate Title=GoldenEye X (5e Clouds)
CRC=FDF95D15 618546CA
RefMD5=E03B088B6AC9E0080440EFED07C1E40F
```

**Comment by Graslu** [comment]
Alright I'll do that later, I am once again having issues with GitHub reading my ini file as if I added and deleted 38k lines...

**Comment by loganmc10** [comment]
The Goldeneye roms look like their reference MD5 points to Perfect Dark, which probably isn't right since they have different save types

**Comment by Graslu** [comment]
It should be right, GoldenEye X is a Perfect Dark ROM hack.

**Comment by loganmc10** [comment]
Ah makes sense, I had no idea

Looks good to me @Narann @richard42

**Pull request merged**
