### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by Gillou68310**
I don't even know what to say here...
Maybe, lot of fixes for the new dynarec ;-)

### CODE REVIEW

**Comment by Narann** [comment]
Hi Guillou! That's huge!

As you are the only one with authority on the new dynarec, I will let @loganmc10 test a little and confirm so I can merge this. :)

**Comment by m4xw** [comment]
> 
> 
> Hi Guillou! That's huge!
> 
> As you are the only one with authority on the new dynarec, I will let @loganmc10 test a little and confirm so I can merge this. :)

Its still a bit of a WIP, theres still a few opcodes to match with the interpreter ;)
This fixes the oot freeze as well and many other issues. What i am specifically excited about is interpreting single instruction for debugging, heh.
He did a good job, currently running regression testing with him on my fork and standalone to catch anything obvious, so please no hasty merges.
The issues have been over a decade old, at this point a few more days dont matter^^

**Comment by loganmc10** [comment]
Yeah I don't really use or understand the new dynarec at all. The changes look more or less localized to the new dynarec, so I'd trust @Gillou68310 on this one

**Comment by m4xw** [comment]
Its what a year of hunting the same bug does for new dynarec 🙈 
This PR is a witch hunt of anything that did hide the oot issue

**Review by richard42 — COMMENTED** [review]
As mentioned, it looks like most of this only pertains to the new dynarec. It would be nice to have some kind of regression tests to make sure that nothing got accidentally broken in this big changeset.  But I am okay with everything that I saw here.

**Review by loganmc10 — APPROVED** [review]

**Review by Jj0YzL5nvJ — APPROVED** [review]
**MSVC versions of NewDynarec finally work!**

Fix issues #572 and gonetz/GLideN64#2473 (**with** `CountPerOp = 0`, even interpreters require `CountPerOp = 1`)

**Comment by loganmc10** [comment]
I was just doing some testing and the English translation of Densha de Go (https://www.romhacking.net/translations/2947/) does not boot using the new dynarec (x64). The original Japanese version works. Both versions work with the Cached Interpreter.

**Comment by Gillou68310** [comment]
Please don't merge anything right now, last commit is under investigation...

**Comment by Jj0YzL5nvJ** [comment]
The current state of this PR is way better than the one in the current master branch...

**Comment by Narann** [comment]
@Jj0YzL5nvJ yes, but @Gillou68310 ask to not merge this PR yet.

**Comment by Jj0YzL5nvJ** [comment]
I actually forgot to mention one tiny issue...

`$ git apply ../mupen64plus-core_new-dynarec-fix.patch`
```
../mupen64plus-core_new-dynarec-fix.patch:1154: trailing whitespace.
  
../mupen64plus-core_new-dynarec-fix.patch:1156: trailing whitespace.
  
../mupen64plus-core_new-dynarec-fix.patch:3019: trailing whitespace.
        
../mupen64plus-core_new-dynarec-fix.patch:3612: trailing whitespace.
    
../mupen64plus-core_new-dynarec-fix.patch:4041: trailing whitespace.
  
warning: squelched 18 whitespace errors
warning: 23 lines add whitespace errors.
```

**Comment by Gillou68310** [comment]
Should be ok to merge!

**Comment by Narann** [comment]
BOOM!

**Pull request merged**
