### PR TITLE
Prevents game freezing unrelated to dynarecs

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
gonetz/GLideN64#2473

### CODE REVIEW

**Comment by loganmc10** [comment]
I believe this probably needs to be reverted.

@Jj0YzL5nvJ @Narann  you can test to confirm, but I don't think Indiana Jones boots with CountPerOp=1 if a save file doesn't exist.

Try deleting any save file you have (Indiana Jones and the Infernal Machine (U) [!].eep) and then boot the game with CountPerOp=1, from what I can see it always hangs/doesn't boot. For whatever reason, if the .eep file exists already, it seems to work

**Comment by Narann** [comment]
Damn, sorry guys, I didn't want to wait for such a simple task. I will revert and let you discuss.

Sorry again.

**Comment by Jj0YzL5nvJ** [comment]
> Try deleting any save file you have (Indiana Jones and the Infernal Machine (U) [!].eep) and then boot the game with CountPerOp=1, from what I can see it always hangs/doesn't boot.

Yes, I can confirm.

> For whatever reason, if the .eep file exists already, it seems to work

Boot up with a * .eep file produced with CountPerOp=0 but hangs with one produced with CountPerOp=1.

**CountPerOp=0**
$ xxd -l 512 "0_Indiana Jones and the Infernal Machine (U) [!].eep"
```
00000000: 02d6 00f3 00f0 0002 0589 01c1 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000f0: 0000 0000 0000 0000 0000 0037 007f ff0b  ...........7....
00000100: 0589 01c1 0000 0000 0000 0000 0000 0000  ................
00000110: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000130: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000140: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000150: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000160: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000170: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000180: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000190: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001f0: 0000 0037 007f ff0b 0000 0000 0000 0000  ...7............
```

**CountPerOp=1**
$ xxd -l 512 "1_Indiana Jones and the Infernal Machine (U) [!].eep"
```
00000000: 0000 0000 0000 0000 ffff ffff ffff ffff  ................
00000010: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000020: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000030: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000040: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000050: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000060: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000070: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000080: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000090: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000000a0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000000b0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000000c0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000000d0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000000e0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000000f0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000100: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000110: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000120: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000130: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000140: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000150: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000160: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000170: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000180: ffff ffff ffff ffff ffff ffff ffff ffff  ................
00000190: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000001a0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000001b0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000001c0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000001d0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000001e0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
000001f0: ffff ffff ffff ffff ffff ffff ffff ffff  ................
```

**Comment by Narann** [comment]
I reverted the commit.

**Comment by loganmc10** [comment]
Yeah it's definitely a weird/interesting issue. I remember looking into it when I was working on improving the compatibility of Indiana Jones. The overall game might actually work better with CountPerOp=1, but for some reason that prevents the initial boot, quite frustrating. I never did figure out a good solution

**Comment by Jj0YzL5nvJ** [comment]
[It looks like an overflow bug in EEPROM initialization.](https://github.com/mupen64plus/mupen64plus-core/blob/06139eecc9adabef4c8d6b5c8870d0084fb5007f/src/main/main.c#L1045)

**Pull request merged**
