### PR TITLE
Allow using compiler other than gcc

### PR DESCRIPTION
**Pull request by loganmc10**

### CODE REVIEW

**Comment by bsmiles32** [comment]
OK, reverted all commits. Thank you for reporting this issue.
Really sorry about this. 3rd time in few days that I break master... :(

**Comment by loganmc10** [comment]
No that was my bad, I didn't realize that make sets the CC variable

**Comment by fzurita** [comment]
You could use a different environment variable other than CC

**Comment by loganmc10** [comment]
It seems that you can still override CC by doing ```make CC=clsng all``` so that should suffice

**Pull request merged**
