### PR TITLE
Netplay fixes from Android port

### PR DESCRIPTION
**Pull request by loganmc10**
I wanted to make sure these don't get missed:

https://github.com/mupen64plus/mupen64plus-core/commit/07a22eeff3188b1141c87c26a7a7bba807185241
https://github.com/mupen64plus/mupen64plus-core/commit/a00ba8dca007fdf939b8d83e5090869144f6a12a

@fzurita perhaps you could comment on the results of the speed limiter change? Do you think it could be merged into the upstream code?

### CODE REVIEW

**Comment by fzurita** [comment]
Yeah, I think the speed limiter change can be merged. It mainly gets rid of the averaging and limits how long it can try to run faster to catch up if we fall behind momentarily.

**Comment by loganmc10** [comment]
I know that @joeldenning experienced some issues with the speed limiter during netplay when he was doing performance/latency testing for Smash Bros.

I'm curious @joeldenning do you think you'd be able to test this change in a way that would tell you if it improved your netplay performance? I know you showed me some frame rate tracking that you were doing at the time.

**Comment by loganmc10** [comment]
I suspect we may not hear back from Joel, @m4xw and @fzurita are you ok with these changes? I believe you've discussed it a bit on Discord?

**Comment by m4xw** [comment]
fwiw it can be cleaned up more

**Comment by loganmc10** [comment]
Do you have specific suggestions?

**Comment by m4xw** [comment]
For example the boolean equation `if(sleepTime > 0 && sleepTime < maxSleepNeeded*SpeedFactorMultiple && l_MainSpeedLimit)` can be optimize to check for `l_MainSpeedLimit` first, saves some unrequired calculations on the `<` case, iirc fzurita had smth in mind as well, can't remember what he meant tho

**Comment by loganmc10** [comment]
Ok I made the suggested optimization

**Comment by loganmc10** [comment]
Ok I've addressed the issues mentioned, any other feedback? I'm eager to merge a more netplay friendly limiter :)

**Comment by loganmc10** [comment]
Still looking for someone to merge this plz

**Pull request merged**
