### PR TITLE
new_dynarec: Fixed invalidate_block

### PR DESCRIPTION
**Pull request by Gillou68310**
get_bounds returns physical address not virtual address

### CODE REVIEW

**Comment by Gillou68310** [comment]
@fzurita I remember retroben complaining about some of his cheat code not working with the new dynarec while working fine with interpreter, this commit might fix a few things for him.

**Comment by fzurita** [comment]
Ok

**Comment by Gillou68310** [comment]
I will create a single PR for new dynarec fixes.

**Comment by fzurita** [comment]
Ok

**Comment by Gillou68310** [comment]
Here's the new branch https://github.com/Gillou68310/mupen64plus-core/tree/new_dynarec_fix
I'll wait @loganmc10's feedback on https://github.com/mupen64plus/mupen64plus-core/issues/158 before creating the new PR

**Comment by Gillou68310** [comment]
Here's what it fix so far:
https://github.com/mupen64plus/mupen64plus-core/issues/170
https://github.com/mupen64plus/mupen64plus-core/issues/171
https://github.com/mupen64plus/mupen64plus-core/issues/179

**Comment by loganmc10** [comment]
Sorry I haven't forgotten about this, I don't have any savestate for Mario Party so I've just been playing it on the train to and from work, but I haven't come across Coin Block Bash yet.

**Comment by Gillou68310** [comment]
No problem ;-)

**Comment by loganmc10** [comment]
Well I finally got there on my phone so now I have a savestate right before the game. It actually worked on Android, so I'll try it on my Raspberry Pi tonight and see if I can reproduce the crash, since that is where I experienced it initially.

**Comment by Gillou68310** [comment]
Cool, don't hesitate to share the savestate so I can test this by my side too.

**Comment by loganmc10** [comment]
I am testing this using RetroArch + GLupeN64, not mupen64plus...

**Comment by Gillou68310** [comment]
Oh yeah I forgot about that. Which version of the core is libretro based on?

**Comment by loganmc10** [comment]
GLupeN64 uses the master branch of mupen64plus-core, the only modifications are to some of the plugin/audio/input code to make it work with libretro, but the dynarec code and all that is unmodified.

**Comment by Gillou68310** [comment]
Well the savestate is compatible then!

**Comment by Gillou68310** [comment]
If they add datas at the end of the savestate it's not a problem. I'll test and report back.

**Comment by Gillou68310** [comment]
You're right it's not compatible :-(

**Comment by loganmc10** [comment]
Sorry I'm an idiot that last file wasn't the save state.... I've attached the actual savestate if you want to try that out :D

[Mario Party (USA) Save State.zip](https://github.com/mupen64plus/mupen64plus-core/files/464925/Mario.Party.USA.Save.State.zip)

**Comment by loganmc10** [comment]
Well I just tried it on the Raspberry Pi and it didn't crash... so I don't know... somehow it works differently with GLupeN64?

I couldn't get the savestate to work with mupen64plus, I just tried to rename it to .st0 and open it, it didn't like it.

Anyway I don't really have the time to test this with mupen64plus so I'm afraid I can't be much more help.

I know I'm not the only one who has run into the Coin Block Bash crash, someone mentioned it on Reddit a while ago:

https://www.reddit.com/r/RetroPie/comments/3ufb7o/anyone_know_how_to_get_any_mario_party_working/

**Comment by Gillou68310** [comment]
Ok I managed to make the savestate work with mp64+. I tried on both x86 and ARM with no crash using current core master.

**Comment by loganmc10** [comment]
Huh well I swear I'm not crazy lol maybe it depends on what nap us being played? I don't remember what map it happened on but it happened twice to me a while ago

**Pull request closed without merging**
