### PR TITLE
Allow building the core with the new dynarec on windows

### PR DESCRIPTION
**Pull request by Gillou68310**
Here's some instructions In order to build with the new_dynarec on windows:

MSVC2010:
-Open mupen64plus-ui-console solution property page
-Select "Configuration Properties"
-Change mupen64plus-core project configuration to New_Dynarec_Debug or New_Dynarec_Release depending if you're building in Debug or Release mode.

MINGW:
Use "make" with NEW_DYNAREC=1

### CODE REVIEW

**Comment by Gillou68310** [comment]
@richard42 Tested and working with mingw, we still need to find someone to test on OSX

**Comment by richard42** [comment]
I can test under OSX in the next few days.

**Comment by Narann** [comment]
As a note, this PR seems to conflict with current master (I guess it's memory re factoring related). Any hope you @Gillou68310 did the merge? Or @bsmiles32?

**Comment by littleguy77** [comment]
Or rebase onto HEAD preferably ;)

**Comment by Narann** [comment]
Of course! :D

**Comment by Gillou68310** [comment]
Update: Rebased against master.

**Comment by Gillou68310** [comment]
> I can test under OSX in the next few days.

@richard42 did you get some times to test this?

**Comment by richard42** [comment]
Sorry I still haven't tested this yet but I will soon.  It shouldn't take too much time; I fixed a bunch of OSX build stuff for Gonetz a month or two ago.

**Comment by Gillou68310** [comment]
Ok no problemo ;-)

**Comment by richard42** [comment]
I was about to merge this (NEW_DYNAREC doesn't build on OSX anyway because clang doesn't like the linkage_x86.S), but it has major conflicts with the head.  Presumably this is due to the 'cenification' changes that were merged.  Can you please rebase this on the head?

**Comment by Gillou68310** [comment]
Sure

**Comment by Gillou68310** [comment]
@richard42 Update: Rebased against master.

**Pull request merged**
