### PR TITLE
Trust plugins to trigger SP interrupts

### PR DESCRIPTION
**Pull request by loganmc10**
This is based on work by @bsmiles32 in https://github.com/bsmiles32/mupen64plus-core/commit/a1b6df0800dd86936b8500cb7b731b10ee8d79ac, brought on by debugging https://github.com/mupen64plus/mupen64plus-core/issues/181

I've tested this ever so briefly on a few games like Super Mario 64 and World Driver Champ. I'm just posting this here to get some feedback and perhaps some testing.

I've also posed a few questions in comments in the code that I was a little unclear on, I'd appreciate if anyone has some insight on those lines.

### CODE REVIEW

**Comment by loganmc10** [comment]
I've tested this with quite a few games now, both HLE and LLE graphics plugins. It seems pretty solid, I don't see any regressions. It does fix the crashing in Top Gear Rally 2, and removes the need for the Perfect Dark hack. I assume it also fixes other stability problems as well.

There are still a few items that I'm not sure if I'm getting right, does ```cp0_update_count(sp->r4300);``` need to appear before every ```add_interrupt_event()``` call?

Also, in the current version it schedules a DP interrupt with a value/counter of 1000. This is necessary for Pokemon detection in Pokemon Snap (probably other things as well). After this change, 1000 no longer worked, but 4000 does. Project64 uses 0x1000 (4096), which is where I got the idea for 4000. But is 4000 right? How are these numbers determined?

**Comment by bsmiles32** [comment]
add_interrupt_event needs an updated COUNT register as all events are compared using it. That's why we make sure to call cp0_update_count before.
As for the other values, I really don't know where they come from. I guess it's purely empirical as everything timing related  is unfortunately.

**Comment by loganmc10** [comment]
Ok understood. I've updated the PR to cleanup the code. I've tested this with quite a few games. Including the ones that have been more sensitive to RSP interrupt changes (Perfect Dark, Kirby, Banjo 1/2, Blast Corps, Pokemon Snap, etc...).

I've played several races in Top Gear Rally 2 and several levels in Perfect Dark, no more crashing.

**Comment by bsmiles32** [comment]
@loganmc10 I also tested on my end and it seems to work correctly. I'm not sure why it works correctly though. I'll merge it now and revert if somebody complains.

**Comment by fzurita** [comment]
I'll get this out to a wider audience and see how many people complain or are happy about it.

**Comment by Gillou68310** [comment]
I don't think this implementation is correct, I don't even understand why it works because no SP interrupts are ever triggered when the RSP is done with a task.

On the real hardware the CPU and RSP run in parallel:
-The CPU starts the RSP
-The RSP process its task while the CPU is still running.
-When the RSP is done with its task it causes an SP interrupt on the CPU side.

On the emulator the CPU and RSP are obviously not running in parallel:
-The CPU starts the RSP
-The RSP process its task
-When the RSP is done with its task an SP interrupt is scheduled with a configurable delay.
-The CPU runs until the SP interrupt is triggered.

The SP interrupt configurable delay is an approximation of the time the RSP spends executing its task.

@loganmc10 If you see this ```Core Warning: two events of type 0x80 in interrupt queue``` it's because the CPU is starting the RSP before the last SP interrupt has been triggered. You could try reducing the configurable delay to see if it fixes the issue.

Now that I think about it we should probably clear ```SP_STATUS_BROKE``` and ```SP_STATUS_HALT``` bits when returning from ```doRspCycles``` and set them back in ```rsp_interrupt_event```.

**Comment by loganmc10** [comment]
> I don't even understand why it works because no SP interrupts are ever triggered when the RSP is done with a task.

The RSP plugin sets the interrupt bit: https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/hle.c#L165

So basically this is the difference between having "DelaySI" on or off. With the way it is now, there is no delay, the SP interrupt is raised the next time interrupts are checked. With the old implementation, we would check if the RSP plugin set the MI interrupt bit, if it did, we would unset it, and schedule the RSP interrupt for later.

The problem with the old implementation is that, like you mentioned, sometimes it would "double up" and schedule a new RSP task before the old one was finished, which caused issues in Top Gear Rally 2, Perfect Dark, and probably other games.

You are probably right, perhaps if we cleared HALT and BROKE after the RSP task, then it would know not to start a new task. I'll try that out sometime today.

**Comment by loganmc10** [comment]
@Gillou68310 actually now that I really look at the RSP plugin, it does:

```
*hle->mi_intr |= MI_INTR_SP;
HleCheckInterrupts(hle->user_defined);
```

So it actually checks the interrupt itself as well, by having the emulator core also call a delayed interrupt, wouldn't we be calling 2 interrupts for the same RSP task?

**Comment by Gillou68310** [comment]
IIRC the ```CheckInterrupts``` API points to an ```EmptyFunc```

**Comment by Gillou68310** [comment]
I just checked and ```rsp_interrupt_event``` is never called!

**Comment by loganmc10** [comment]
No I totally agree, see https://github.com/mupen64plus/mupen64plus-core/pull/371

**Comment by Gillou68310** [comment]
Well I was not expecting such great results :-)

**Pull request merged**
