### PR TITLE
New dynarec fix

### PR DESCRIPTION
**Pull request by Gillou68310**

### CODE REVIEW

**Comment by fzurita** [comment]
@Gillou68310 After this pull request, Conker's bad far day is now crashing on RomClose. Here is the back trace:

```
Build fingerprint: 'motorola/quark_verizon/quark:5.1/SU4TL-44/44:user/release-keys'
pid: 5500, tid: 7356, name: CoreThread  >>> org.mupen64plusae.v3.alpha <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x57940030
#00 pc 00052f6c  /data/app/org.mupen64plusae.v3.alpha-1/lib/arm/libmupen64plus-core.so: Routine ll_clear at mupen64plus-core/src/r4300/new_dynarec/new_dynarec.c:1158
#01 pc 0007ee44  /data/app/org.mupen64plusae.v3.alpha-1/lib/arm/libmupen64plus-core.so: Routine new_dynarec_cleanup at mupen64plus-core/src/r4300/new_dynarec/new_dynarec.c:7754 (discriminator 3)
#02 pc 0004217c  /data/app/org.mupen64plusae.v3.alpha-1/lib/arm/libmupen64plus-core.so: Routine r4300_execute at mupen64plus-core/src/r4300/r4300.c:274
#03 pc 00012288  /data/app/org.mupen64plusae.v3.alpha-1/lib/arm/libmupen64plus-core.so: Routine main_run at mupen64plus-core/src/main/main.c:1013
#04 pc 00003ef9  /data/app/org.mupen64plusae.v3.alpha-1/lib/arm/libmupen64plus-ui-console.so (SDL_main+3536): Routine SDL_main at mupen64plus-ui-console/src/main.c:782
#05 pc 007a3e55  /data/app/org.mupen64plusae.v3.alpha-1/oat/arm/base.odex (offset 0x4c3000) (int paulscode.android.mupen64plusae.jni.NativeExports.emuStart(java.lang.String, java.lang.String, java.lang.Object[])+144)
#06 pc 007948fb  /data/app/org.mupen64plusae.v3.alpha-1/oat/arm/base.odex (offset 0x4c3000) (void paulscode.android.mupen64plusae.jni.CoreInterface$4.run()+2470)
#07 pc 71cf78d1  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1f68000)
PS C:\Users\Francisco\Documents\workspaces>

```

**Comment by Gillou68310** [comment]
Fixed by https://github.com/mupen64plus/mupen64plus-core/pull/192
This was a long standing issue, when do_dirty_stub_ds was called it was referencing the MIPS source code from the last recompiled block instead of the current one.

**Comment by fzurita** [comment]
Gotcha, thanks.

**Comment by fzurita** [comment]
I wonder why even though it was an issue before, it didn't crash before.

**Comment by Gillou68310** [comment]
The old design was using a static circular buffer, so the problem was not noticeable. See https://github.com/mupen64plus/mupen64plus-core/commit/bbf2d25e9e90bd96a305aa113f65aaad1889c762 commit details for more info.

**Pull request merged**
