### PR TITLE
Alternative implementation of "Don't deal with save states when RSP t…

### PR DESCRIPTION
**Pull request by bsmiles32**
…ask is locked"

See https://github.com/mupen64plus/mupen64plus-core/pull/534

### CODE REVIEW

**Comment by loganmc10** [comment]
The only real difference I see is that rsp_task_locked is stored in the save state right? So when we load a save state you should probably set the flag there as well

**Comment by bsmiles32** [comment]
rsp_task_locked is indeed stored inside the savestate, but it may not be needed anymore now that we prevent savestating when rsp_task_locked is set... so updating interrupt_unsafe_state inside the save state loading doesn't much sense as it must be 0 to begin with.
Maybe I should also remove the rsp_task_locked variable from the savestate ?

**Comment by loganmc10** [comment]
Oh right it must always be 0 with this change. I would just leave it, who knows if it may be used in the future again

**Comment by bsmiles32** [comment]
Squashed a small copy paste error which completely broke old savestates loading. Should be fixed now.

**Pull request merged**
