### PR TITLE
Dyna start

### PR DESCRIPTION
**Pull request by Gillou68310**
@bsmiles32 I switched from objdump to nm and created an awk script to generate the asm defines, the script is shared between all platforms . I can confirm that it works on windows (both msvc and mingw), osx 10.12 (llvm8) and Ubuntu(gcc) for both 32bit and 64bit architectures.

### CODE REVIEW

**Comment by bsmiles32** [comment]
Cannot test ATM but looking good. You should add nasm to the .travis.yml so it is installed un the build env.

**Comment by bsmiles32** [comment]
And update the readme for prerequisites

**Comment by Gillou68310** [comment]
Done
Also I moved asm_defines.c to a new asm_defines folder, headers will be generared in that folder and the folder is included at compile time. This is usefull for android where headers are generated for all platforms before compilation even started. Is that ok for you?

**Comment by bsmiles32** [comment]
Okay for me. Good work !

**Comment by Gillou68310** [comment]
I still need to check if the PIC version is working otherwise this is ready for merging.

**Comment by Gillou68310** [comment]
@fzurita I updated the mupen64plus-core.mk in order to support my latest changes:
https://github.com/mupen64plus-ae/mupen64plus-ae/tree/dyna_start

It builds fine on both ubuntu and windows with ndk-r13b.
Could you check if it's running fine on real devices?

**Comment by Gillou68310** [comment]
asm_defines headers are generated for each platforms before compilation, you can find them in 
mupen64plus-core\src\asm_defines\armeabi-v7a
mupen64plus-core\src\asm_defines\x86
mupen64plus-core\src\asm_defines\x86\pic (mupen64plus-core-pic variant)

**Comment by Gillou68310** [comment]
I just checked the PIC version on ubuntu and everything seems to work fine :-)

**Comment by fzurita** [comment]
Sure, I'll try it once I get the chance. I've been pretty busy lately with the GLideN64 refactor.

**Comment by Gillou68310** [comment]
Lol yeah I noticed, I'm deleting almost 30 emails per day about GlideN64 refactor ;-)
There's no rush here anyway.

**Comment by Gillou68310** [comment]
@richard42 before you merge this, I'm currently adding PIC support for linkage_x86.asm.

**Comment by Gillou68310** [comment]
@fzurita I added PIC support for linkage_x86.asm so there's no need to build the mupen64plus-core-pic variant anymore. I updated the android build file consequently:
https://github.com/mupen64plus-ae/mupen64plus-ae/commits/dyna_start

**Comment by fzurita** [comment]
That's awesome, hopefully that means that at can build with clang. I will try that next

**Comment by Gillou68310** [comment]
I'm building with clang on osx without any issue.

**Comment by fzurita** [comment]
@Gillou68310 I'm finally getting around to building your branch here: https://github.com/mupen64plus-ae/mupen64plus-ae/commits/dyna_start

I'm not having much luck though:
```
A subdirectory or file jni\mupen64plus-core\src\asm_defines\armeabi-v7a already exists.
Assembler messages:
Fatal error: can't create C:/Users/Francisco/Documents/workspaces/mupen64plus-ae/app/src/main/jni/mupen64plus-core/src/asm_defines/armeabi-v7a/asm_defines.o: No such file or directory
The system cannot find the path specified.
C:/Users/Francisco/android-sdks/ndk-bundle/build//../prebuilt/windows-x86_64/bin/awk.exe: can't open file C:/Users/Francisco/Documents/workspaces/mupen64plus-ae/app/src/main/jni/mupen64plus-core/src/asm_defines/armeabi-v7a/asm_defines.dump
 source line number 3
```

**Comment by Gillou68310** [comment]
Weird I don't have this issue. What's your ndk version? Also are you building on windows or linux?

**Comment by fzurita** [comment]
I'm building in Window, NDK version is latest. I think I found the problem though. In mupen64plus-core.mk, if I replace:

```
$(shell mkdir jni\mupen64plus-core\src\asm_defines\$(TARGET_ARCH_ABI))
```

with 

```
        $(shell mkdir src\main\jni\mupen64plus-core\src\asm_defines\$(TARGET_ARCH_ABI))
```

It seems to work ok. Not sure why the "current directory" is different between you and me.

**Comment by fzurita** [comment]
Probably just using this should work with everyone:

```$(shell $(LOCAL_PATH)\mupen64plus-core\src\asm_defines\$(TARGET_ARCH_ABI))```

**Comment by Gillou68310** [comment]
I was building from command line within the app/src/main folder that's probably the difference. I didn't use the LOCAL_PATH variable because of the forward slash issue on windows.

**Comment by fzurita** [comment]
I used LOCAL_PATH just now from Android studio and it worked fine.

**Comment by Gillou68310** [comment]
Probably because the armeabi-v7a folder already exists, try to delete it and try again.

**Comment by fzurita** [comment]
Errr... you are correct

**Comment by fzurita** [comment]
I think I'll just leave it like this: 
```
$(shell mkdir src\main\jni\mupen64plus-core\src\asm_defines\$(TARGET_ARCH_ABI))
```

**Comment by Gillou68310** [comment]
Or you can ask android studio to run the ndk-build command from within the app/src/main folder ;-)

**Comment by fzurita** [comment]
Hmm.... the non-PIC version runs a LOT faster on the nexus player (x86). Also, I made a few updates to your branch.

**Comment by fzurita** [comment]
I think I'm going to merge to master. It seems to work well enough.

**Comment by Gillou68310** [comment]
PIC code is expected to be slower on x86 unfortunately.

**Comment by fzurita** [comment]
Right, we were using the old PIC version. The new PIC version is a lot faster.

**Pull request merged**
