### PR TITLE
new_dynarec: Code cleanup

### PR DESCRIPTION
**Pull request by Gillou68310**
@bsmiles32 I noticed that both mingw and osx new dynarec build are broken because the AWK command does not match the objdump structure.

MinGW: [mingw.txt](https://github.com/mupen64plus/mupen64plus-core/files/754459/mingw.txt)
OSX: [llvm8.txt](https://github.com/mupen64plus/mupen64plus-core/files/754458/llvm8.txt)

Do you think it's possible to fix this issue with a generic AWK command? Or do we need to have a specific command for all platforms?

Also newer version of objdump might change the dump format, so a generic command would be preferred ;-)

### CODE REVIEW

**Comment by bsmiles32** [comment]
I'm afraid platform specific commands is required here...

**Comment by bsmiles32** [comment]
Or maybe use nm instead of objdump, which seems to have a more standardized output ?

**Comment by Gillou68310** [comment]
I check nm and you're right outputs are much more similar between platforms.

osx:
```
0000000000000001 C _offsetof_struct_cached_interp_invalid_code
0000000000000225 C _offsetof_struct_cp0_count_per_op
0000000000000221 C _offsetof_struct_cp0_last_addr
0000000000000219 C _offsetof_struct_cp0_next_interrupt
0000000000000001 C _offsetof_struct_cp0_regs
0000000000000229 C _offsetof_struct_cp0_tlb
0000000001104391 C _offsetof_struct_device_mem
0000000000000001 C _offsetof_struct_device_r4300
00000000011041c9 C _offsetof_struct_device_ri
0000000000000011 C _offsetof_struct_memory_address
0000000000000009 C _offsetof_struct_memory_wbyte
0000000000000009 C _offsetof_struct_memory_wdword
0000000000000009 C _offsetof_struct_memory_whword
0000000000000009 C _offsetof_struct_memory_wword
0000000000000ae9 C _offsetof_struct_r4300_core_cached_interp
0000000000900c29 C _offsetof_struct_r4300_core_cp0
0000000000000101 C _offsetof_struct_r4300_core_hi
0000000000000109 C _offsetof_struct_r4300_core_lo
0000000000000001 C _offsetof_struct_r4300_core_regs
0000000000000a11 C _offsetof_struct_r4300_core_return_address
0000000000000a09 C _offsetof_struct_r4300_core_save_rip
0000000000000a01 C _offsetof_struct_r4300_core_save_rsp
0000000000000135 C _offsetof_struct_r4300_core_stop
0000000000000029 C _offsetof_struct_rdram_dram
0000000000000021 C _offsetof_struct_ri_controller_rdram
0000000000000681 C _offsetof_struct_tlb_LUT_r
0000000000400681 C _offsetof_struct_tlb_LUT_w
0000000000000001 C _offsetof_struct_tlb_entries
```

Mingw:
```
00000000 b .bss
00000000 d .data
00000000 i .drectve
00000000 r .rdata$zzz
00000000 t .text
00000001 C _offsetof_struct_cached_interp_invalid_code
00000199 C _offsetof_struct_cp0_count_per_op
00000195 C _offsetof_struct_cp0_last_addr
0000018d C _offsetof_struct_cp0_next_interrupt
00000001 C _offsetof_struct_cp0_regs
0000019d C _offsetof_struct_cp0_tlb
00d03c41 C _offsetof_struct_device_mem
00000001 C _offsetof_struct_device_r4300
00d03ae1 C _offsetof_struct_device_ri
00000011 C _offsetof_struct_memory_address
00000009 C _offsetof_struct_memory_wbyte
00000009 C _offsetof_struct_memory_wdword
00000009 C _offsetof_struct_memory_whword
00000009 C _offsetof_struct_memory_wword
00000655 C _offsetof_struct_r4300_core_cached_interp
0050071d C _offsetof_struct_r4300_core_cp0
00000101 C _offsetof_struct_r4300_core_hi
00000109 C _offsetof_struct_r4300_core_lo
00000001 C _offsetof_struct_r4300_core_regs
000005cd C _offsetof_struct_r4300_core_return_address
000005b5 C _offsetof_struct_r4300_core_save_ebp
000005b9 C _offsetof_struct_r4300_core_save_ebx
000005c1 C _offsetof_struct_r4300_core_save_edi
000005c9 C _offsetof_struct_r4300_core_save_eip
000005bd C _offsetof_struct_r4300_core_save_esi
000005c5 C _offsetof_struct_r4300_core_save_esp
0000012d C _offsetof_struct_r4300_core_stop
00000029 C _offsetof_struct_rdram_dram
00000021 C _offsetof_struct_ri_controller_rdram
00000001 C _offsetof_struct_tlb_entries
00000681 C _offsetof_struct_tlb_LUT_r
00400681 C _offsetof_struct_tlb_LUT_w
```

Do you know an easy way to detect the leading underscore and remove it if necessary with awk?

**Comment by bsmiles32** [comment]
Use the substr function

**Comment by Gillou68310** [comment]
Yeah I know about the substr function, my question was more about how to conditionally use it to remove the leading underscore if one exists?

**Comment by ddugovic** [comment]
`([0-9a-f]{8} C )_(\w+)` seems to work on regex101.com .  I don't remember sed/awk syntax.

**Pull request merged**
