### PR TITLE
Added PD hack entries

### PR DESCRIPTION
**Pull request by Graslu**
GoldenEye X and Perfect Dark Plus entries added to mupen64plus.ini

### CODE REVIEW

**Comment by loganmc10** [comment]
Something is wrong with this commit: https://github.com/mupen64plus/mupen64plus-core/pull/962/commits/26193305f58baa2012821a5584fc5914bd3fac59 It seems to have edited the entire file? Maybe different line endings? Github wont show the changes

**Comment by loganmc10** [comment]
Also, since Perfect Dark Plus has the same requirements as regular PD, you can just reference the MD5 of the main entry:

```
[5D72155E00Bf2CAB41B0F4A2f2E09C61]
GoodName=Perfect Dark Plus
CRC=FB453D58 AD565422
RefMD5=7F4171B0C8D17815BE37913F535E4E93
```

**Comment by Graslu** [comment]
> Also, since Perfect Dark Plus has the same requirements as regular PD, you can just reference the MD5 of the main entry:
> 
> ```
> [5D72155E00Bf2CAB41B0F4A2f2E09C61]
> GoodName=Perfect Dark Plus
> CRC=FB453D58 AD565422
> RefMD5=7F4171B0C8D17815BE37913F535E4E93
> ```

That should be the case for GoldenEye X as well, should all they be on the same spot?

**Comment by loganmc10** [comment]
> should all they be on the same spot?

I'm not exactly sure what you mean by this, you can do ```RefMD5=<other md5>``` to reference the settings of another ROM, rather than including them. Some INI entries do this, others don't, I guess it's just up to the author, just an FYI

**Comment by Graslu** [comment]
I didn't read correctly sorry, fixing the issues atm and I'll add the references as they're all the same.

**Comment by Graslu** [comment]
Closing this PR and re-doing it properly, sorry again for the mistake.

**Pull request closed without merging**
