### PR TITLE
Fix compilation of new dynarec.

### PR DESCRIPTION
**Pull request by bsmiles32**
reported by @fzurita in PR #510

### CODE REVIEW

**Comment by joolswills** [comment]
I can't find this commit in the source tree - has someone rebased/force pushed master ?

**Comment by joolswills** [comment]
see https://github.com/mupen64plus/mupen64plus-core/issues/517

**Comment by joolswills** [comment]
Sorry - I had a brain glitch - I read this as merged. ignore me :)

**Comment by bsmiles32** [comment]
try something like that in your mupen64plus directory :
git remote add bsmiles32 https://github.com/bsmiles32/mupen64plus-core
git fetch bsmiles32
git checkout bsmiles32/arm_compile_fix
cd project/unix
make clean && make DEBUG=1 all

**Pull request merged**
