### PR TITLE
[WIP] Refactor memory

### PR DESCRIPTION
**Pull request by bsmiles32**
This is the first part of the memory subsystem refactoring [1].

The goal of this set of commits is twofold:
-first remove the duplication that exists between byte,hword,word and dword accesses to memory
-second remove some global variables associated with memory accesses (address, rdword, cpu_byte, hword, word, dword)

Issues:
- break the new_dynarec (If someone more knowledgeable than me can look what to change to make it work again)
- use interpreted functions for memory accesses in the dynarec (I didn't know how to rewrite them, so I need help here).

I'd like to hear about any regression (behavior/performance), especially from downstream since I can't really test that.

cc: @richard42, @fayvel, @mupen64plus-ae, @twinaphex

[1] I have some more commits waiting to be cleaned up in my branch refactoring_experimental :)
Those will come later.

### CODE REVIEW

**Comment by richard42** [comment]
Good work.  Has this been tested with the ARM target of the new dynarec?

**Comment by littleguy77** [comment]
No, the ARM codepath does not currently build.  @bsmiles32 prepended "[WIP]" to the PR title to indicate that is is not ready to merge yet.  I suppose he could close the PR and reopen when ready, though that makes it harder to rebase and update the PR as he and @Gillou68310 work through the issues.  Some more discussion here:
http://www.paulscode.com/forum/index.php?topic=1814.0

**Comment by bsmiles32** [comment]
@richard42: I'm not sure how much time will be needed to make this PR work with the new dynarec
(and honestly I might loose interest...). Since the problematic part comes with the last 2 commits, would you allow to merge the other commits (from "2e2d4c0" to "a1af202" included), so that I can move on with other refactorings ?
If so, should I make a new PR with the commits to merge and update this PR accordingly ?

**Comment by littleguy77** [comment]
I pulled commit a1af202 into mupen64plus-ae and everything compiled fine.  One linker error however:
```
[x86] SharedLibrary  : libmupen64plus-core.so
linkage_x86.s:679: error: undefined reference to 'rdram'
linkage_x86.s:690: error: undefined reference to 'rdram'
linkage_x86.s:701: error: undefined reference to 'rdram'
linkage_x86.s:712: error: undefined reference to 'rdram'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [obj/local/x86/libmupen64plus-core.so] Error 1
```

**Comment by littleguy77** [comment]
Ah, never mind.  I just fixed changed the varnames from `rdram` to `g_rdram` at the locations specified above and it linked fine.

**Comment by Narann** [comment]
So, @bsmiles32 and @Gillou68310 just to be sure: What you both suggest is:
* Merge @bsmiles32 commits from https://github.com/bsmiles32/mupen64plus-core/commit/2e2d4c0c39440dda9385fd44a237667c496dbf61 to https://github.com/bsmiles32/mupen64plus-core/commit/a1af20276309f9074a696d58e0f5b1dd9abcc109.
* Then integrate @Gillou68310 work.
* Then @bsmiles32 will continue to work on the new_dynarec to finish it.

Am I right?

I also thing it's not a good situation for both of you so if you agree on a kind of "trade of" plan that would be great. :)

Please guys, don't give up! :dancer:

**Comment by bsmiles32** [comment]
Just a quick reply before work. Tonight i'll make a new PR with non conflicting commits. And update this PR accordingly. Anyway thanks for quick and helpful feedback :)

**Comment by richard42** [comment]
I'm okay with merging everything but the last 2 commits.

**Comment by littleguy77** [comment]
:+1:

**Comment by bsmiles32** [comment]
Update:
-Non conflicting commits are now part of the "preliminary memory refactoring" PR (#59).
-Fix memory reads/writes in case of exception. This caused weird behavior notably in Armorine.

**Comment by bsmiles32** [comment]
Update: Rebased against master.

**Comment by Narann** [comment]
@bsmiles32 have you anyone particularly that you would like to see testing before merge? I don't know, @Gillou68310 maybe?

**Comment by bsmiles32** [comment]
This is still not ready for merge. It misses modifications for the arm backend. Plus i will need to update the x86 assembler part to Intel syntax after the merge of gillou's work.

**Comment by Narann** [comment]
Oups, sorry, I was thinking only the two latest commits where a problem and you rebase everything to make the merge possible. :)

**Comment by Nebuleon** [comment]
I became aware of this pull request today with #88.

I must say the two last commits try to bite off way more than they can chew. You tried to change the mechanism by which TLB Refill exceptions were reported, the memory accessor helpers (a single read function instead of `readmem[addr >> 16] ();`), and the ABI of memory accessors themselves - which broke all JITs -, then tried to eliminate global variables while not knowing what to do with `CHECK_MEMORY`.

4 months later or so, with #83 and its `invalidate_r4300_cached_code` function, as well as some memory refactorings merged already, perhaps it'd be easier now to make `CHECK_MEMORY` be a call to that instead, and you can pass `address` or a local variable, whatever you wish. It would then be easier to kill the global variable while keeping the `void (*) (void)` functions that the JITs use, as simple wrappers to your redone 3-parameter functions:
```C
void read_???()
{
  address = new_read_???(address, rdword, 4);
}
```

This still has massive potential for breakage on the New Dynarec/ARM however, due to its peculiar global variables.

**Comment by bsmiles32** [comment]
Closing as a new memory refactoring attempt has been made.

**Pull request closed without merging**
