### PR TITLE
Add RISC-V Support

### LINKED ISSUE #897: CPU type "riscv64" not supported.
Upon attempting to build from git, I get the following error.
```
Makefile:139: *** CPU type "riscv64" not supported.  Please file bug report at 'https://github.com/mupen64plus/mupen64plus-core/issues'.  Stop.
```

### PR DESCRIPTION
**Pull request by archanox**
Resolves #897 for mupen64plus-core

### CODE REVIEW

**Comment by Narann** [comment]
Looks good to me, but I would love to know how does it run?

**Comment by archanox** [comment]
Without a dynarec, not well. But I'll put a video capture up hopefully today.

**Comment by archanox** [comment]
> Looks good to me, but I would love to know how does it run?

https://youtu.be/5vn0IyB2xqM
Judge for yourself, but I wouldn't deem this very playable with the cached interpreter. But the good news is that the port from MIPS to RISC-V dynarec should be relatively straight forward.

**Comment by Narann** [comment]
Thanks for the video! :)

**Pull request merged**
