### PR TITLE
Fix mingw build

### PR DESCRIPTION
**Pull request by loganmc10**
Fixes https://github.com/mupen64plus/mupen64plus-core/issues/603

### CODE REVIEW

**Comment by loganmc10** [comment]
Tested and working on my PC

**Comment by Gillou68310** [comment]
Is there no macro shared between both mingw and visual studio? WIN32 maybe?

**Comment by loganmc10** [comment]
_WIN32 seems to work on MinGW, I assume it works in Visual Studio as well. I've updated the PR

**Comment by Gillou68310** [comment]
Thanks I'll check on visual studio

**Comment by Gillou68310** [comment]
Looks good

**Pull request merged**
