### PR TITLE
[WIP] Pass pointer to fcr31 around in fpu.h functions to avoid usage of g_dev.

### PR DESCRIPTION
**Pull request by bsmiles32**
Reopening this PR with the hope of fixing the remaining issue with ARM dynarec.

### CODE REVIEW

**Comment by bsmiles32** [comment]
@Gillou68310 I also assigned you this one as you are way more competent for finding why this breaks the ARM dynarec.

**Comment by Gillou68310** [comment]
```emit_readword((u_int)&g_dev.r4300.new_dynarec_hot_state.fcr31,ARG1_REG);```

The above will read the value of fcr31 into ARG1_REG.

To read the address of fcr31 into ARG1_REG you should use:

```emit_movimm((u_int)&g_dev.r4300.new_dynarec_hot_state.fcr31,ARG1_REG);```

**Comment by loganmc10** [comment]
I tried the fix suggested on Android (https://github.com/loganmc10/mupen64plus-ae/commit/ca1feba28f3d05b583a99954d34f1bcd7ec61baf)

It seems to work, no segfaults anymore.

**Comment by bsmiles32** [comment]
@Gillou68310 : Thank you or looking into this, I wouldn't have guessed myself :)
@loganmc10 : Also thanks for testing @Gillou68310 suggestion, I had already done the fix myself some days ago, but couldn't push them because was offline for a couple of day.

**Pull request merged**
